### ISSUE TITLE
Add .fed.rep.br 

### ISSUE THREAD

**Issue by internationalnic** [publicsuffix/list#1073]
Please add .fed.rep.br (extension with acronym for Federative Republic of Brazil).

Should the .fed.rep.br extension be included in the private section or ICANN section?

Have an excellent day!

**Comment by dnsguru** [comment]
@fnevesbr is this a PR you can submit if this is appropriate?   choose the location (ICANN/PRIVATE) as you believe is best

**Comment by dnsguru** [comment]
Recent changes in .BR #1068

**Comment by internationalnic** [comment]
@dnsguru I will include fed.rep.br in the private section!

**Comment by FederalNIC** [comment]
@dnsguru How about including the .fed.rep.br extension in the private or ICANN section?

We saw that you have already done an excellent job of merging PR, with the necessary settings.

Now we should just make a TXT record, right?

.fed.rep.br is not operated by NIC.BR.

The Federal NIC is the operator of the extension .fed.rep.br

**Comment by fnevesbr** [comment]
Jothan,

On Wed, Jul 22, 2020 at 1:07 PM Jothan Frakes <notifications@github.com>
wrote:

> @fnevesbr <https://github.com/fnevesbr> is this a PR you can submit if
> this is appropriate? choose the location (ICANN/PRIVATE) as you believe is
> best
>
No. This is a private third level registration. If registered should go on
the PRIVATE section.

Frederico

**Comment by FederalNIC** [comment]
How about including the .fed.rep.br extension in the private or ICANN section?

We saw that you have already done an excellent job of merging PR, with the necessary settings.

Now we should just make a TXT record, right?

.fed.rep.br is not operated by NIC.BR.

The Federal NIC is the operator of the extension .fed.rep.br

**Comment by FederalNIC** [comment]
+// Federal NIC - Federative Republic of Brazil: http://www.federalregistry.fed.rep.br
+// Submitted by Lucas Junho <info@federalregistry.fed.rep.br>
+fed.rep.br

**Comment by internationalnic** [comment]
If we were to consider the question of whether an extension is operated or not, the extensions used by governors are not operated by NIC.BR and were included without the operators of each extension knowing about it.

Some examples:

.es.gov.br
.mg.gov.br
.sp.gov.br
.go.gov.br and etc ...

**Comment by FederalNIC** [comment]
@dnsguru Hello, I would like to get more information about this case.

Which .fed.rep.br extension will be included in which section?

Thank you :)

**Comment by internationalnic** [comment]
@dnsguru Who can send a PR to include .fed.rep.br?

I can? You or Frederico?

Or who will do this PR for inclusion?

**Comment by dnsguru** [comment]
@internationalnic you would submit a PR for the initial issue to add .fed.rep.br - this will require placing specific text record in the DNS for fed.rep.br to validate the administrative control of the zone.

For the various .gov.br zones listed above in  [your prior comment](https://github.com/publicsuffix/list/issues/1073#issuecomment-662889541), those would need to be submitted by their respective zone operator/administrators with the ability to place txt records in the DNS zones in order to validate them.

**Comment by internationalnic** [comment]
Is it already decided in which section the PR should be included?

This is the first time that I will do this, so I will try.

**Comment by FederalNIC** [comment]
@internationalnic Since you are interested in doing this, I will give you permission to do PR on our behalf.

I hope you get it!

**Comment by FederalNIC** [comment]
@internationalnic Read the wiki and @dnsguru guidelines carefully.

**Comment by internationalnic** [comment]
@FederalNIC I do not promise that I will be able to do this PR, because as I informed you, this is the first time that I do this for the company.

I hope it works. 😅

**Comment by internationalnic** [comment]
@FederalNIC I tried to create a PR but I didn't quite understand how to do it.

I read the instructions and what @dnsguru  wrote, but I was confused.

I'm sorry!

**Comment by FederalNIC** [comment]
@dnsguru What are the chances of a PR going wrong?

**Comment by dnsguru** [comment]
No need to speculate about chance - perhaps @FederalNIC it would be wise to reduce chance and have someone do this for you that manages the DNS so that they can update the appropriate record to validate / verify the PR # submission once assigned.  

As discussed above, this would go in the PRIVATE section of the PSL.

**Comment by FederalNIC** [comment]
@dnsguru I asked you this question, as many Brazilian developers do not know how to create a PR.

Even in our company, we asked 4 people to do a PR and they did not succeed.

After several attempts I chose to hire developers to do a PR Fed.rep.br, but I think they don't know how to do it.

I had to present a Wikipedia page on PSL created by our boss when he was a Wikipedia editor and they still didn't understand.

https://pt.m.wikipedia.org/wiki/Public_Suffix_List

**Comment by FederalNIC** [comment]
@dnsguru Don't get me wrong, but most Brazilian developers don't seem to have learned about domains, DNS and PSL at the university.

**Comment by FederalNIC** [comment]
@dnsguru I honestly don't know how to include fed.rep.br in a private section.

I did some tests and read the wiki and documentation, but I still don't know how to create and change this file for inclusion.

Currently, there are already sites like:

brazil.fed.rep.br
Mercosur.fed.tep.br
br-ipo.fed.rep.br
brazilcsirt.fed.rep.br
attorneygeneral.fed.rep.br

And our .fed.rep.br domain registration website

www.federalnic.fed.rep.br

However, I don't know how to do this process. I'm confused!

**Comment by fsodic** [comment]
> @dnsguru I honestly don't know how to include fed.rep.br in a private section.
> 
> I did some tests and read the wiki and documentation, but I still don't know how to create and change this file for inclusion.
> 
> Currently, there are already sites like:
> 
> brazil.fed.rep.br
> Mercosur.fed.tep.br
> br-ipo.fed.rep.br
> brazilcsirt.fed.rep.br
> attorneygeneral.fed.rep.br
> 
> And our .fed.rep.br domain registration website
> 
> [www.federalnic.fed.rep.br](http://www.federalnic.fed.rep.br)
> 
> However, I don't know how to do this process. I'm confused!

just **fork** publicsuffix/list repo and edit in your repo.
Maybe this official documentation help you https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo 

And you can put in the appropriate procedure so that this issue can be closed (Actually this is not an issue)

**Comment by FederalNIC** [comment]
@fsodic Hello, thanks for your help!

There is no way to do this procedure, because the people responsible for doing this, are with COVID-19 and have not been removed.

The company is already providing home office service, but in Brazil, due to bureaucracy, it is not possible for everyone to stay in the home office.

I will announce that we are hiring someone to work in the home office who knows how to do this.

If not, I will close this issue! :)

**Comment by internationalnic** [comment]
@dnsguru Wouldn't it be better to close this Issue, as there is no one to make this inclusion?

**Comment by internationalnic** [comment]
Closed for lack of someone to do the inclusion.

**Comment by dnsguru** [comment]
@internationalnic thanks for closing... Just re-submit once you're resourced to perform the required tasks, and reference this issue

**Comment by internationalnic** [comment]
@dnsguru By the way, what is necessary to do in: #820? 

https://github.com/zonedb/zonedb/commit/3f3c46e341991151f3f0203e6b004be43db749b7
