### ISSUE TITLE
cloudapp.azure.com not included in Azure special-case public suffix list

### ISSUE THREAD

**Issue by mzpqnxow** [publicsuffix/list#1137]
Hello,

I recently noticed that while a bunch of Azure "special" domains are handled- e.g. `azurewebsites.net`, `cloudapp.net`, etc. the `cloudapp.azure.com` domain is not. An example from Azure looks like this:

`<private>.cloudapp.azure.com`

Is this something that should be added to `public_suffix_list.dat` or are entries only added when directed by the owner of the domain(s)? In this case, Microsoft.

Thanks

**Comment by dnsguru** [comment]
@mzpqnxow thanks for the q - submissions in the #private section require the administrator of a domain to include special records into the zone file of the domain name in question, so that chain of authority can be validated.  Microsoft are the party with control over that domain name and its DNS.

Microsoft would need to submit this, at their determination.  @miwebst or @mostafaez recently submitted a PR for some elements in the Azure domains list.  People tend to move around in companies but @jluk also had submitted.

Others from MS may monitor this repo, and if so, raising this issue may elevate their attention to taking action (or not).

**Comment by mzpqnxow** [comment]
Thank you for the quick and detailed explanation, I thought this may be the case. Please feel free to close this issue, or we can leave it open for a little while to see if anyone from MSFT notices, whatever you think is most appropriate

Thanks again

**Comment by dnsguru** [comment]
Closing, but  @miwebst or @mostafaez  please review

**Comment by chrislittle** [comment]
@mzpqnxow can you confirm that adding *.cloudapp.azure.com would work for you. the entry would prevent cookies from being set at eastus.cloudapp.azure.com or westus.cloudapp.azure.com, but would allow cookies to be set below level 3 (e.g. cookies could be set for foo.eastus.cloadapp.azure.com domain).

**Comment by mzpqnxow** [comment]
@chrislittle that works for me, for my purposes it's significantly better than the current situation

**Comment by chrislittle** [comment]
Thank you @mzpqnxow this is currently going up the chain internally to get this entry created.
