### ISSUE TITLE
Handling EBERO TLDs (ex: .wed)

### ISSUE THREAD

**Issue by martimlobao** [publicsuffix/list#1174]
The list seems to be missing 3 valid TLDs, which are included on IANA.org: https://data.iana.org/TLD/tlds-alpha-by-domain.txt

Namely:
* .wed
* .xn--q7ce6a (and equivalent .ລາວ)
* .xn--mgbcpq6gpa1a (and equivalent .البحرين)

**Comment by dnsguru** [comment]
Being discussed in PR #1175

**Comment by dnsguru** [comment]
We should put to rest the .WED TLD discussion, as it was terminated and should not be present.
See: [ICANN gTLD JSON file, note "ContractTerminated": "True" for wed entry](https://www.icann.org/resources/registries/gtlds/v2/gtlds.json)

With respect to the IDNccTLDs for Bahrain and Laos, there's no official notice from the IANA or ccNSO when IDN ccTLDs process, so we rely on the community or the repsective NIC to submit these, so thank you for submitting these.

**Comment by dnsguru** [comment]
Thank you for splitting the PR for this into separate issues for the IDN ccTLDs for Bahrain and Laos (#1175) / .WED (#1176) , and for your submission and interest in helping keep the PSL fresh and updated.

We were able to merge in #1175, but #1176 is a little trickier due to it being a new precedent.  This Issue may sit open for a while.  .WED domains do exist in the wild, but the TLD is in EBERO state, which is ambiguous as to who to discuss the state of inclusion / exclusion from the PSL.

My bias towards keeping the issues/PR flowing into a closed state had me quickly thinking that .WED being overlooked by the automation and excluded from the PSL by automation was appropriate.

The typical scenario of TLDs which have been marked as cancelled in the ICANN .json file are those which did not "open" or "launch" and thus contain no names other than the nic.[tld] or registry-reserved names.  In the case of those TLDs which flow into EBERO, that is not a valid assumption, as there may be customers with valid registrations within those strings.

My instinct is to proclaim that individual site owners with legacy registrations within .WED are able to open PR to set their domains' options within the PRIVATE section.  IF a legacy registrant has a viable entry in the .WED zone that delegates DNS in the .WED zome to their nameservers, they would be about to validate their authoritative administration of that subdomain. 

This does not stretch to fit some of the non-browser use-cases of the PSL whereby someone is looking to it as some authoritative listing of TLDs for their logic flow governing (lower case "g") that they should expect to see and allow for addressing (ie, a web-form not accepting a .WED website URI where validating input field submissions, a mail system might bounce email from a legitimate, existing  .WED registration, etc).

Will leave this issue and the .WED PR open for comments and inputs from the community.

**Comment by dnsguru** [comment]
At first thought, I was going to make the case to ICANN to perhaps add an 'isEBERO' = true to the json, but there's a way to glean if a TLD is EBERO from layering [the IANA TLD list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) and [the ICANN Contracting of gTLDs JSON file](https://www.icann.org/resources/registries/gtlds/v2/gtlds.json).

It seems that the IANA list should be authoritative in the situation where a TLD is flagged as a cancelled TLD in the ICANN gTLDs JSON file vs just skipping those.

This is really an atypical scenario that .WED raises, as TLDs now seem to change hands vs sliding into EBERO needs.

**Comment by dnsguru** [comment]
I think this needs to be elevated to be about EBERO TLDs and open dialog with ICANN about paths for handling inclusion or exclusion of these.  Once a TLD is placed into EBERO, it is not taking new registrations, but can be functional for existing registrations.
Renaming this to : Handling EBERO TLDs (ex: .wed)
