### ISSUE TITLE
Updating .YE ccTLD Publicsuffix list

### ISSUE THREAD

**Issue by myagout** [publicsuffix/list#1182]
Dears, 
We at TeleYemen have read your guidelines
and we would like to update .ye in the list as follows.

kindly if there is an issue in the below format let me now. and if you require verification of someway 
drop me a comment on how to verify that I am a part of TeleYemen Team and I will surely do.

// ye: you can contact .YE Technical Team through https://www.teleyemen.com.ye/en/contact-us
*.ye
*.com.ye
*.net.ye
*.gov.ye
*.edu.ye

Best Regards,

**Comment by dnsguru** [comment]
Hello - This appears to be submitted by a newly created github account.  There are protections in place to validate a submission does not impact or disrupt an existing namespace, so there is a need for you to create a pull request that makes these changes, and then place entries into the respective zone files of authority for these TLDs.  This is done in order to validate that you have administrative control of the zone(s) being submitted.  See the notes in the comments inside of this link #897

**Comment by bsolomon1124** [comment]
@dnsguru I received an email reply noting that the txt records were applied.

```bash
$ dig @8.8.8.8 txt _psl.com.ye
;; ANSWER SECTION:
_psl.com.ye.		21599	IN	TXT	"https://github.com/publicsuffix/list/pull/897"
```

Is it necessary that @myagout be the one to open the pull request here?
