### ISSUE TITLE
Need confirmation to fix side effect

### ISSUE THREAD

**Issue by gchap** [publicsuffix/list#1209]
Hello there,

I'm currently working for OVHcloud and we have an issue related to https://github.com/publicsuffix/list/pull/1193

We need to generate a certificate for XXX.hosting.ovh.net but we can't anymore due to the above pull request.
This is a side effect that we did not anticipate and we are looking to a way to permit it.

Can you confirm us that, if we add the below line in the list, we will be able to generate a certificate for XXX.hosting.ovh.net :
```
hosting.ovh.net
```

Thank you in advance for your help
Gaëtan

**Comment by dnsguru** [comment]
@gchap Can turn this around quickly, but due to the fact that you are a different person than the party that submitted #1193, we will need you to update the _psl text record to reflect the #1211 so that we can validate/verify that what you're submitting is tied to the zone that you're seeking to change.

This keeps third parties from affecting zones not under their control.

**Comment by sleevi** [comment]
> Can you confirm us that, if we add the below line in the list, we will be able to generate a certificate for XXX.hosting.ovh.net 

No.

Which is to say, no, it's not guaranteed. That's something that you should be asking your CA, because it's ultimately your CAs policies around how they use/consume the PSL, and not anything intrinsic within the PSL itself. e.g. CAs can issue certs today, with your current entry, if they do certain validation steps (e.g. by validating proofs at a level one-label removed from those matching suffices). Whether or not your CA does this, or requires you to use additional local programs (e.g. if the ACME challenge needs to be modified to reflect that, from the client), that's moreso between you and your CA.

**Comment by dnsguru** [comment]
Closing based upon #1211
