### ISSUE TITLE
.name domains are not properly handled

### ISSUE THREAD

**Issue by darrenoh** [publicsuffix/list#1280]
Some .name domains may only be registered as third-level domains. Verisign does not allow two-letter names or any name that has a registered third-level domain to to be registered as second-level domains. For example, Verisign considers oh.name to be a TLD. darren.oh.name and eiren.oh.name must be registered separately. As a result, browsers treat third-level domains registered to different owners as the same site.

The DNS verification process should be changed to allow owners of third-level .name domains to list the second-level domain as a TLD or private domain.

**Comment by sleevi** [comment]
Fortunately or unfortunately, depending on your point of view, this is not something we can support, as captured at https://github.com/publicsuffix/list/pull/277 . It's a design of the DNS that the PSL is simply unable to accommodate (e.g. see https://github.com/publicsuffix/list/pull/277#issuecomment-309222300 )

**Comment by darrenoh** [comment]
I'm not suggesting that PSL try to include all registry-operated .name domains. My suggestion is that the DNS verification process for private domains not treat .name registrants as third-party users.

**Comment by dnsguru** [comment]
I see the point being made here, I think.

If my surname were "example", and I could not register example.name
directly because it was set aside as a surname, I could register
perfect.example.name.  So would someone be able to set a super cookie for
example.name because it was not PSL'd.

Would have to loop in the Registry on handling this, and that is a
challenge because there are a lot lot lot of surnames established in the
.name TLD
