### ISSUE TITLE
What list are test_psl.txt and tests.txt based upon?

### ISSUE THREAD

**Issue by alevesely** [publicsuffix/list#1321]
Both the TEST DATA paragraph of the official [list page](https://publicsuffix.org/list/) and this `tests` folder propose a a test suite without mentioning what list should it be run against.  Obviously, it is not the *real* list, because it doesn't contain `example` as a TLD, and because it wouldn't make sense to have a rather stable test suite aimed at a moving target.

Maybe I'm stupid, but I'm unable to determine what list should I use to run the tests.  There must be one, as I see @bkirz in issue #208 had problems with leading dots, not with `example` TLD.  Would someone clarify this point, please?

**Comment by dnsguru** [comment]
These are automated tests of what strings would find their way into PSL (or not) and how to enumerate them.

What various projects do with the information in the PSL varies.  Downline projects that the PSL propogates into don't all use the list as it may require some teaks to suit their purposes.  Some remove things, some add things.

What are you hoping to accomplish / what's behind the question?

**Comment by alevesely** [comment]
For example, one of the tests is:
```C
checkPublicSuffix("a.b.example.example", "example.example");
```
Leaving aside whether `checkPublicSuffix` is implemented as a macro and how, the test should recognize that `example` is a public suffix.  In order to pass that test, I had to `echo example >> fulltest.dat`.  Hm... now that I'm writing I recall that bullet 2 of the spec says _If no rules match, the prevailing rule is "*"_, which I'm not clear how to interpret.  My implementation returns null on non-existing TLDs, and that is consistent with `example.local` being commented out.

Anyway, let's consider another example.  We don't know how the Japanese city of [Kobe](https://en.wikipedia.org/wiki/Kobe) is going to evolve.  Maybe they stick forever to:
```
*.kobe.jp
!city.kobe.jp
```
If that will change, the _list_  will change accordingly, but the algorithm and the implementations will likely remain the same.  To update `test_psl.txt` in order to track list changes is an unneeded extra burden.  In addition, implementations shouldn't be expected to upgrade the test suite unless the _algorithm_ changes, also because that might need fixes (I had to change single quotes to double quotes, for example).

So, an implementation can build its own list, more or less like I did with `fulltest.dat` above, such that it passes all the tests.  However, passing all the test with my cooked list would hardly be considered significant by anyone else.  It would be cleaner if the [list page](https://publicsuffix.org/list/) could say something like

> There is a [short set of test data](https://raw.githubusercontent.com/publicsuffix/list/master/tests/test_psl.txt) available. You will need to define a checkPublicSuffix() function which takes as parameter a domain name and the registrable part of the domain, runs your implementation on the domain name and checks the result is the registrable domain expected **according to the test list**. Thanks to Rob Stradling of [Comodo](http://www.comodo.com/) for providing this test data. 

The test list could also contain strange constructs that don't (yet) happen in the real Internet.

**Comment by dnsguru** [comment]
OK - is this a remaining question or a suggestion at this point?

**Comment by alevesely** [comment]
The question is where/what the reference test list is meant to be.  If there's isn't any, you may consider it a suggestion to create one.  Yet, I wonder against what has the test data been used thus far...

**Comment by dnsguru** [comment]
Because we're volunteers here, we're always looking for volunteer help vs taking on more assignments - are you volunteering scope or help?    Would you like to write and contribute what you're suggesting towards making the test vs test data more clear, if you're seeing it as deficient?

**Comment by sleevi** [comment]
@alevesely The reference list is the PSL itself.

If I understand, you'd like the test of the PSL algorithm to be independent of the PSL itself. Presumably, this is so that you can convert the existing data file into something specific to whatever language or tooling you use, where, along with the supposed reference list, you can test the PSL independent of the PSL.

I'm not sure that's necessarily a desirable outcome. The potential concern you're raising - "What if the PSL changes, then the tests would have to change too" is not unreasonable a concern, but perhaps not a very compelling one, compared to the alternative being proposed here. Under that scenario, we, the PSL maintainers, would need to ensure that any PSL list changes have equivalent, but hypothetical, changes to the reference data list file, to make sure that we're exercising equivalent functionality. Further, the conversion of the tests into some language-specific test still means that any time the PSL tests update, all dependent projects also have to re-convert all the tests.

However, the most important issue that the proposal overlooks is that part of the reason we added the tests was to try and provide a test suite that encourages implementers to not only test their implementation of the algorithm, but how they parse and understand the PSL itself. The tests, by depending on the PSL list, help ensure that whatever changes to the PSL (such as the ICANN vs PRIVATE section) are successfully handled by implementations. If we change the format in a way that causes implementations to misparse, the hope is that the failure will be picked up by them performing similar tests, and crisis will be averted. With this proposed outcome, we'd have to ensure that we effectively have a shadow, test-only datafile that we more or less keep in logical sync with the actual PSL, and that's significantly more maintenance work for an unclear (if any) benefit.

I think we may want to close this as WontFix, if I've understood correctly, but I admit, I may have fully misunderstood the concern here.

**Comment by alevesely** [comment]
I uploaded a [strawman](https://github.com/alevesely/publicsuffix) to illustrate the concept.  It contains a `fulltest.dat`, the _test list_, obtained from the list by adding a few non-Internet elements.  It also contains a slightly modified copy of `test_psl.txt`, the _test data_.

**The _test list_ might need changes only when the _test data_ changes**.  This would only happen when the algorithm changes, when a relevant question arises or when an implementation pitfall is discovered.  Such events require the attention of the PSL maintainers anyway.

> If we change the format in a way that causes implementations to misparse, the hope is that the failure will be picked up by them performing similar tests

Implementations might issue errors or warnings in case of parsing errors.  Otherwise, any misinterpretation won't be noticed unless a specific test is added to the test data, or discovered by chance.  I'm not clear whether you expect implementations to add _similar tests_ in order to exercise new list entries.  I don't think that happens, because the list changes too frequently to afford scrutinizing the diff in order to pick out any formatting novelties and devise appropriate tests.  Errors found while loading the list can be logged and might be noticed by end users, though.

The basic fact which I think needs to be fixed is that the test data (after language adaptation) produces failures in an apparently correct implementation.  When compiled with the regular [test data](https://raw.githubusercontent.com/publicsuffix/list/master/tests/test_psl.txt), the test included in the strawman produces three errors against the current PSL.  When compiled with the augmented test data, it produces no error against the test list.

**Comment by sleevi** [comment]
I think we’re making progress, because rather than fixing on your preferred solution, we’re making progress on the problem description.

> the test included in the strawman produces three errors against the current PSL. 

Please provide clear information about what three entries you’re referring to.

If it is the `example` entries, that’s a bug in your implementation, not the test, because non-existent TLDs should still follow the wildcard rule. You absolutely should not return null for a non-existent entry if correctly implementing the algorithm.

**Comment by alevesely** [comment]
> > the test included in the strawman produces three errors against the current PSL.
> 
> Please provide clear information about what three entries you’re referring to.

```
ale@pcale:~/tmp/zdkimfilter/regdom/regdom-mytake/take2$ ./test new_list.dat -t| grep expect
example.example: expect example.example, have NULL
b.example.example: expect example.example, have NULL
a.b.example.example: expect example.example, have NULL
```

> If it is the `example` entries, that’s a bug in your implementation, not the test, because non-existent TLDs should still follow the wildcard rule. You absolutely should not return null for a non-existent entry if correctly implementing the algorithm.

Hm... maybe?  I guess that's why the local tests are commented out.  I uncommented them and my buggy implementation didn't fail:
```C
// Listed, but non-Internet, TLD.
checkPublicSuffix("local", NULL);
checkPublicSuffix("example.local", NULL);
checkPublicSuffix("b.example.local", NULL);
checkPublicSuffix("a.b.example.local", NULL);
```
I see some implementations have options to skip that rule.  In some cases that gives strange inconsistencies, as in `non-registrable.za`, as mentioned in #570 and #689.  In the strawman test list I added entries to test recursion, like so:
```
bcd.efg.hij.klm.nop.qrs.tuv.wxy.z
bcd.efg.*.klm.*.qrs.tuv.*.z
bcd.*.*.*.nop.*.*.*.z
```
I checked a couple of implementations against that, but they appeal to the wildcard rule and just return `z` as the public suffix, notwithstanding the input domain matches.

Do you think it would make sense to have  a branch of implementations that omit that rule?  In that case, a test list can be of use for such branch.

**Comment by sleevi** [comment]
> Hm... maybe? I guess that's why the local tests are commented out. 

Correct, they are commented out, because returning `null` for them is not the correct output, because of the prevailing `*` rule.

> I see some implementations have options to skip that rule.

As an API parameter, yes, if they're using the PSL to try and determine if a domain is in the root zone database. There's some related discussion on https://github.com/publicsuffix/list/issues/160

However, with respect to the algorithm, the algorithm is the algorithm. These implementations are using the PSL for things other than public suffices when they're using an API parameter that disables the wildcard rule.

>  In some cases that gives strange inconsistencies, as in `non-registrable.za`, as mentioned in #570 and #689. In the strawman test list I added entries to test recursion, like so:
> 
> ```
> bcd.efg.hij.klm.nop.qrs.tuv.wxy.z
> bcd.efg.*.klm.*.qrs.tuv.*.z
> bcd.*.*.*.nop.*.*.*.z
> ```

Multiple wildcards within an entry are not well supported - which is why they're not part of the test suite. That's https://github.com/publicsuffix/list/issues/145

> Do you think it would make sense to have a branch of implementations that omit that rule? In that case, a test list can be of use for such branch.

No. No implementation omitting that rule complies with the PSL algorithm, and they aren't returning the public suffix.

That they're using the PSL for something else is, well, their decision. I think most browsers support an API that uses the PSL both to determine the public suffix and to determine if something is "domain-shaped". The "domain-shaped-ness" is its own element of controversy and complexity (since, ideally, they would talk to the root servers by way of a recursive resolver), but sure, it makes sense not to ship multiple separate datafiles. Some of this was captured at https://bugzilla.mozilla.org/show_bug.cgi?id=1139842 and https://bugzilla.mozilla.org/show_bug.cgi?id=958299

I'm think this issue is WontFix, because it does seem like it was/is a misunderstanding, and not a structural issue. Getting the wrong result for the (uncommented) `example` domains, but the "right" (but also wrong) result for the disabled bits, is a sign of an implementation bug not implementing the prevailing `*` rule from the algorithm.

At best, removing the commented-out lines seems to be a source of the confusion, but lines are commented out for a reason. We could delete those, however.

**Comment by alevesely** [comment]
I added an option `-c` to my [test program](https://github.com/alevesely/publicsuffix).  It took just two lines of code after exiting the main loop:
```C
		if (comply_with_wildcard_rule && best_match == 0 && i == 0)
			best_match = 1;
```
This proves that the wildcard rule can be added on top of the algorithm.  The only tricky point is to export `i` from the loop, to detect whether there was a match at all.  Otherwise I'd get three errors (the last one from an added test):
```
bd: expect NULL, have bd
ck: expect NULL, have ck
notregistrable.za: expect NULL, have za
3/97 errors
```
I think that noting the discretionary nature of the wildcard rule would bring the important consequence of legitimating the results obtained without it.  That's granting citizenship to the "domain-shaped-ness".

I also re-commented out the `.local` tests, so the test passes irrespective of option `-c`.

As for the augmented _test list_, it allows to check support for multiple wildcards.  The ability to match a domain against all rules (rule 1) is not less important than the wildcard rule (rule 2).  I think you have to insist on that, otherwise you might reach a point where they'd be needed but cannot be used because that would break major implementations.

**Comment by dnsguru** [comment]
So I think the question "What list are test_psl.txt and tests.txt based
upon?" is answered now.

We would like to close this issue and congratulations on your test
functions for your purposes.

Each of the various projects, libraries, etc that use or integrate the PSL
are able to subsequently apply their own logic or algorithms, so I believe
it sounds like you have arrived at your destination safely.

**Comment by dnsguru** [comment]
Closing now.  Post if this needs re-opening
