### ISSUE TITLE
Missing TLDs

### ISSUE THREAD

**Issue by jschauma** [publicsuffix/list#1394]
Looking at the IANA root zone (https://www.iana.org/domains/root/files) and comparing TLDs listed there versus TLDs found in the public suffix list, I noticed the absence of the following TLDs:

wed.
za.

Since these are IANA assigned TLDs, shouldn't they be added to the PSL?

**Comment by dnsguru** [comment]
Thank you for taking time to make this review.  Because we're all volunteers, every little bit helps.  

It appears that there has been some review and updates to this issue since filed, which narrowed it down to 2 TLDs, and I'll mention them below with a response as I close this issue out, so that it (hopefully) explains things.

> wed.
relates to #1176 where this is discussed.
wed is in the root, but is a special circumstance called 'EBERO' that has a file from ICANN indicating that the TLD is cancelled.
#1325 

> za.
This ccTLD is accurately represented in the PSL 

According to the registry, [ZADNA](https://www.zadna.org.za/content/page/domain-information/), .za does not directly accept registrations at second level.  At least currently.

**Comment by jschauma** [comment]
Thanks for the explanation!

**Comment by dnsguru** [comment]
@jschauma - thank you, and I appreciate your project that enumerates the various DNS record types.
