### ISSUE TITLE
Special use .local domain missing

### ISSUE THREAD

**Issue by jamescridland** [publicsuffix/list#1466]
See [RFC 6762](https://datatracker.ietf.org/doc/html/rfc6762).

Use here would enable .local domains to be correctly parsed for services like password managers, and the like, which consume this public suffix list.

**Comment by dnsguru** [comment]
Thanks James - The .local TLD is not new with respect to the PSL or ultimately how browsers or other downline intergrators / consumers of the PSL would implement (we have zero control over that).  Because the .local behaviour is 'local' to how the status quo works, each time this comes up the ultimate outcome has been that .local won't be updated in the list.
