### ISSUE TITLE
Incorrect spelling of "Submitted" might cause parsing errors

### ISSUE THREAD

**Issue by Scarjit** [publicsuffix/list#1529]
The PSL currently has 6 counts of incorrectly spelled "Submitted" (that i could find):
https://github.com/publicsuffix/list/blob/d7634211f7d6cce97ac89c3580cdc251aa6511c8/public_suffix_list.dat#L10826

https://github.com/publicsuffix/list/blob/d7634211f7d6cce97ac89c3580cdc251aa6511c8/public_suffix_list.dat#L12171

https://github.com/publicsuffix/list/blob/d7634211f7d6cce97ac89c3580cdc251aa6511c8/public_suffix_list.dat#L12214

https://github.com/publicsuffix/list/blob/d7634211f7d6cce97ac89c3580cdc251aa6511c8/public_suffix_list.dat#L12324

https://github.com/publicsuffix/list/blob/d7634211f7d6cce97ac89c3580cdc251aa6511c8/public_suffix_list.dat#L12347

https://github.com/publicsuffix/list/blob/d7634211f7d6cce97ac89c3580cdc251aa6511c8/public_suffix_list.dat#L10826

This could cause parsing errors for libraries.

**Comment by dnsguru** [comment]
Thank you for this review - not all parties include the word 'Submitted' (spelled correctly or otherwise), so hopefully nobody has any dependencies written for this. 

These typos are perfectly natural, and I want to get through a backlog with the volunteer (my) cycles before addressing this as it seems non-critical.   

We often receive submissions where English is not the primary language, and do not alter the information on the comment line that the submitting party enters, but I would be curious if there may be a template being used for these which needs updating that these are sourced from.

**Comment by Scarjit** [comment]
No problem, i just noticed it, while writing a script to validate the _psl.domain TXT records for each privat entry on this list (https://gist.github.com/Scarjit/da7663bfd5a6754a1b41bb7cffe4032f).
