### ISSUE TITLE
Tld addition to the PublicSuffix List

### ISSUE THREAD

**Issue by Aastha009** [publicsuffix/list#153]
[TLDs_to_be_added.txt](https://github.com/publicsuffix/list/files/135630/TLDs_to_be_added.txt)

**Comment by weppos** [comment]
@Aastha009 the list contains several suffixes that are already listed. We updated the most recent suffixes today (#163)

I'm closing this ticket. Feel free to open a new one if you should find missing TLDs, but please only provide relevant information (and possibly directly in the ticket rather than an attachment, unless it's a valid `.diff` or `.patch` file).
