### ISSUE TITLE
Add reserved testing TLDs from RFC2606

### ISSUE THREAD

**Issue by dveditz** [publicsuffix/list#1537]
It would be nice if the testing TLDs reserved in RFC 2606 (updated in RFC 6761) behaved like a real TLD for testing purposes (for example, could be counted on to isolate cookies for sibling domains from each other). The following should be added to the PSL:

example
localhost
test

".invalid" is also reserved but it seems unnecessary to add to the PSL since it [should return DNS lookup errors](https://www.rfc-editor.org/rfc/rfc6761.html#section-6.4).

I'd be happy with just the original RFC 2606 reserved TLDs, but we could also consider adding
* ".local" (rfc 6762)
* the [IANA-reserved IDN test domains](https://www.iana.org/domains/reserved), though that's currently marked "experimental" and I have no feel for how likely those might end up being permanent.

**Comment by dveditz** [comment]
This does not satisfy the desire for a public service as described in #1349, but these TLDs are both reserved for and in common use for internal testing scenarios.

**Comment by sleevi** [comment]
@dveditz We've discussed this several times, including with @gerv , and ultimately decided not to.

e.g https://github.com/publicsuffix/list/pull/2 and https://bugzilla.mozilla.org/show_bug.cgi?id=1161102

The question, I think, is what special behaviour would be granted by adding these, given the extant `*` rule. Those generally seem to highlight [bugs in assumptions](https://github.com/sleevi/psl-problems) - but if there are places in browsers where this distinction now matters, perhaps its worth digging into, because they'll also have issues with new TLDs?

**Comment by dnsguru** [comment]
We have a good discussion in #1515 on this more recently.   The crux of this is there is strong reticense to affectation of status-quo norms and expected behavior widely via PSL change vs allowing application developers to do their own thing.

**Comment by dveditz** [comment]
@dnsguru I am confused about the state of this issue. I assumed the "wontfix" I saw in mail was the end of it (in bugzilla it closes an issue), and I accept the discussion above that led to that decision. I just realized this still "open". Is it waiting for me to close it?  But you assigned it to yourself at the same time as applying the wontfix label so maybe there's some undocumented task spun out of this?

I'm happy to close it or have it closed; this issue seems to have come to an end.

**Comment by dveditz** [comment]
I'm going to assume the reason is the same as https://github.com/publicsuffix/list/pull/1515#issuecomment-1034022167

> Rather than closing this now, will leave as a wontfix and let discussion or updates happen if they will.
> Talk us out of this being a wontfix, basically.
