### ISSUE TITLE
gov.al has no A record in DNS 

### ISSUE THREAD

**Issue by DG12** [publicsuffix/list#1552]
from the LIST
http://www.ert.gov.al/ert_alb/faq_det.html?Id=31

**Comment by dnsguru** [comment]
@dg12 thank you for pausing your magic before you got too far down the alphabetical path...   

Please see #1439 

What would be more help vs "help" for this incredibly thinly-resourced project would be for you to not just point out stuff that is broken, but also hunt for and provide the correct link for the resource.  Otherwise, these are not actionable and will likely just stack up more technical debt for the volunteers to maybe be able to eventually get to.

**Comment by DG12** [comment]
What should I create as a pull request for something like this one ert.gov.al
As gov.al has no A record?

gov.al.			18000	SOA	ns1.nic.al. domain.akep.al. 1649269023 10600 3600 1209600 7200
gov.al.			18000	NS	ns1.nic.al.
gov.al.			18000	NS	ns2.nic.al.
gov.al.			18000	NS	nsx.nic.al.
gov.al.			18000	NS	rip.psg.com.

Whois remarks includes
http://www.akep.al/sq/regjistrim-domain

for   ert.gov.al NXDOMAIN

**Comment by dnsguru** [comment]
Here's the thing... what if they are using it internally on their private
networks and removing this impacts browsers for government users.  I
realize it is a thin counterpoint, but we have specific validation rules
for the ICANN and PRIVATE sections that are in place to keep third parties
(that would be you or I privately)

Would need to speak with someone in Admin/control of the AL ccTLD directly
and have them provide some confirmation/validation - can you connect that
up?

**Comment by groundcat** [comment]
I do not believe `gov.al` should be removed from the PSL because a Google search for 'site:gov.al' reveals numerous operational websites of Albania government bodies on the domain.
https://www.google.com/search?q=site%3Agov.al
