### ISSUE TITLE
Remove `js.org` from PSL, no longer offers NS records

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [publicsuffix/list#1660]
js.org should be removed from the Public Suffix List as they no longer offer NS records and has been like that since June 3rd, 2020 (see commit [13b500](https://github.com/js-org/js.org/commit/13b500fe13a5b8cdfe2fc8c431a2da5820f77975)).

Comment regarding NS record allocation: https://github.com/js-org/js.org/blob/master/ns_active.js#L26

Please see comment by a maintainer referencing NS record allocation: https://github.com/js-org/js.org/pull/7786#issuecomment-1306477628

**Comment by MattIPv4** [comment]
js.org still actively offers CNAME records to users with acceptable content for the project.

This has always been js.org's primary mode of operation.

NS records were a short-lived experiment for the project that lead to too much abuse of the domain as a whole for our liking.

**Comment by MattIPv4** [comment]
cc @indus

**Comment by indus** [comment]
JS.ORG in fact did not offer NS records at the time it was listed in the PSL. If availability of NS records for users is a hard requirement then JS.ORG shouldn't be in the PSL.
But if the 3000+ subdomain in public use (growing by ~20/month) are sufficient, I don't see why it should be removed?!

@WilliamDavidHarrison Because we've been coming across each other a lot lately (to be honest - with mixed feelings on my side), I wanted to ask if there's been anything that I've done to upset you?

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison Because we've been coming across each other a lot lately (to be honest - with mixed feelings on my side), I wanted to ask if there's been anything that I've done to upset you?
No, all good.

**Comment by WilliamDavidHarrison** [comment]
> NS records were a short-lived experiment for the project that led to too much abuse/risk of the domain as a whole for our liking (we can check usage/content with CNAME records, and can do cleanups each year, not so with NS records).

I didn't know that, I understand a bit more now.

But also, if those record types were an experiment why are those subdomains still kept and not just moved to CNAME records?

**Comment by MattIPv4** [comment]
Because NS and CNAME records are not the same, and that'd break the subdomains for the folks that we did offer NS records to? Just because we ended up opting to no longer allocate NS records doesn't mean the existing records are an issue -- same way we didn't remove all the CNAME records that no longer meet our updated requirements for relevancy to JavaScript, they were grandfathered in as existing records.

**Comment by dnsguru** [comment]
This is a good discussion.  Could it occur elsewhere?

**Comment by WilliamDavidHarrison** [comment]
> Because NS and CNAME records are not the same, and that'd break the subdomains for the folks that we did offer NS records to? Just because we ended up opting to no longer allocate NS records doesn't mean the existing records are an issue -- same way we didn't remove all the CNAME records that no longer meet our updated requirements for relevancy to JavaScript, they were grandfathered in as existing records.

Ahh ok.

**Comment by indus** [comment]
> This is a good discussion.  Could it occur elsewhere?
@dnsguru So I request to close this. Sorry.
