### ISSUE TITLE
Adding Review of PR domains in #PRIVATE against virustotal or other safety checks

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1699]
There is a cascading "myth of trust" that inclusion in the PSL seems to infer.

Looking for feedback from PSL community about this concept.  *Are you for or against the idea?*

Introducing the concept of review of #PRIVATE section requests against "Realtime Blackhole List" (RBL) on domain names within a Pull Request would help ensure that PSL entries have better inherent trust.

This would mean that for every PR that comes in, the reviewer would check the domains in it (+ re-review a modified section's domains if it is an update) against an RBL and reject entries (or remove them) when there is a positive match against RBL entries.

*Pros:*

* Ensuring that the inclusion of a string as an eTLD+ in the PSL does not introduce inappropriate trust of untrustworthy resources is something that would benefit the public interest.
* Because of the voluntary nature of browser / etc other services PSL use, this type of safety-add helps provide a cleaner namespace which preserves the ongoing attraction to use of the PSL

*Cons:*

* This project is limping on scarce resources, introducing an additional step to review submitted domains in a Pull Request (or section) against an RBL for a "hygiene review" introduces significant overhead to the processing time and turnaround.
* RBLs often have lack of appeals at many RBL may have some friendly fire scenarios that disqualify safe domains, and domains which get RBL listed and can't remediate might inappropriately direct their emotional energy or appeal pleas at PSL volunteers

**Comment by WilliamDavidHarrison** [comment]
I agree with this, as some domains being submitted may be suspicious and / or malicious, so having an automated check will make maintainers lives slightly easier.

**Comment by danderson** [comment]
A couple thoughts that make me lean "no" on RBL consultation at this layer...

## PSL use in threat intelligence

There may be a bit of a chicken and egg problem I expect some threat intelligence tools use the PSL as a hint for "span of control" of a URL, i.e. if malware is being served from a.b.c.com should they mark all of c.com as malicious?

So, for private inclusion requests that cover things like dynamic DNS services, they may show up as flagged precisely because the RBL operators don't have any hint that subdomains are unrelated, and so taint the entire domain for a single bad URL. Conversely, getting onto the PSL and having that trickle to the RBL operators may cause the domain to show as clean again down the road, with the badness signals more precisely scoped to harmful subdomains.

(we could get into a whole argument over how much responsibility hosting providers should shoulder for user-generated content, but down that road seems to lie the erasure of the entire private section of the PSL...)

## Badness evolves

IIUC, the proposal above would be a point in time smell test of a domain at the time that it requests inclusion. I don't think this will be very effective, because attackers and malware move around the internet as they get detected and pushed out of old hosts.

I'd say it's a near certainty that a domain, even an initially clean one, will end up hosting some amount of badness if it allows user-generated content.

So, rather than try to imbue the PSL with an additional meaning of domain trustworthiness, IMO it should remain a "neutral" descriptor of how authority is carved up within a domain, and badness checking should get implemented downstream closer to point of use, by a system that can react closer to real-time to changes (e.g. safe browsing checks).

**Comment by simon-friedberger** [comment]
I would agree with @danderson. I think the aim of the PSL is to describe areas with separate responsibility not to evaluate the trustworthiness of the resources served at those origins. Presumably, having the eTLD on an RBL would also impact the eTLD+1.

@dnsguru Since you marked this "Volunteer Opportunity" could you provide some more information of what you're wanting volunteers to do?

**Comment by simon-friedberger** [comment]
Putting on my security hat, my main concern is that, performing such checks would make people rely on such checks at which point they become required and also a target for attackers. I don't think that is something that is manageable with the slim resources available on the PSL project.

**Comment by dnsguru** [comment]
Your point is not lost, but it dances with some additional knowledge on what integrators do with the PSL when doing what they do.  The reality is that it is also being presented that the threshold of which the need exists has already been passed through - numerous projects alter their behaviour related to security outcomes based upon the presence of an entry vs the absense.  

I'm really not seeking to do a LOT here, and I am the last person seeking to make there be MORE work for the volunteers 
 - I have probably approaching $1M USD in salary equivalent volunteered time across 15 years, and not looking to expand the bleed of my time by expanding the scope of work, hence automation was hoped to provide some data inputs that can inform the review process when looking at a pull request.  
 
 Signals/hits do not necessarily have to be a full-blocker on the Pull Request - it seems fair that there would often be some opportunity for a submitter to 'splain why they have multiple hits on virustotal or why they are blocked by google safe search.  
 
 What is more problematic is projects that pop up and request entries because they seek to work around security limits or moaning that because they are not listed in the PSL they are being targeted by google safe browsing and their not being added is the cause of all their problems vs the abuse they are experiencing (or worse, contributing enablement to).
 
 The right thing to do seems to be to have a few people weigh in here - but doing nothing really subjectively feels wrong.

**Comment by simon-friedberger** [comment]
Could you maybe elaborate a bit more on what you are trying to achieve? Maybe present a few cases that you think are problematic?

If I understand you correctly, the problem is that people will request PSL-addition because some of their users host questionable content and they ended up on safe browsing. And they are trying to compartmentalize while they should really do something about the questionable content. However, if that is the case they still have a valid reason to get added to PSL, right?

**Comment by dnsguru** [comment]
Sure.. I think the core issue is how to know the difference among the following requests.  It does not currently exist that we can differentiate:

A] an entry with the intent to set up subdomains for abuse and benefit from delayed takedown or other affectation that comes from being in the PSL

B] an entry that has some abuse happening from third parties in their subspace from customers or third parties

C] an entry with no abuse ocurring

The objective is to allow additional data to be used in order to inform the review in order to reduce scenario A, and allow an appropriate conversation to occur.

**Comment by mozfreddyb** [comment]
I want to agree with @danderson, especially the second point: Whatever checks we do, they are not going to be useful, permanent attributes as content & DNS entries will be able to evolve. 
I'm pretty sure that common badware lists (e.g., safebrowsing) are trying to blocklist subdomains if a domain is on the PSL, but I'm also pretty sure that they would block everything regardless if the threat persists.

Furthermore, I don't think we should make any kind of third party "security rating" part of the inclusion criteria for the PSL. I'd personally want to lean heavily on automation and "hard" inclusion criteria. The less subjective assessment the better.
