### ISSUE TITLE
add second level domains for ClouDNS

### ISSUE THREAD

**Issue by boyanpeychev** [publicsuffix/list#1713]
[#1593](https://github.com/publicsuffix/list/pull/1593) - this PR is for second level domain names used in ClouDNS for dynamic dns. TXT records are added, you can proceed with the merge.

**Comment by dnsguru** [comment]
no nudges please they distract volunteer cycles

**Comment by boyanpeychev** [comment]
Hello @dnsguru, I'm not sure if I understand your merge cycle correctly, but initial issue for the merge is closed [#1703](https://github.com/publicsuffix/list/issues/1703) as invalid. The merge will be somehow approved without an issue or we have to do something else?

**Comment by WalshyDev** [comment]
The PSL is run by volunteers, their cycles are limited. The PR has already had a first pass and it's now in the queue for another.

Whether it's good or not in it's current state will require another review, that will come just not immediately.

Please be patient and wait for the queue to be processed.

Spending volunteer time on this issue is only delaying the PR being reviewed right now, so please, just be patient :)
