### ISSUE TITLE
[BUG]Special character - High Impact

### ISSUE THREAD

**Issue by Treenity** [publicsuffix/list#1735]
Hi, 

A problem is impacting a lot of project due to a special public suffix "aéroport.ci" with a HUGE impact (unexpected error, causing vendors.js to stop working)

<img width="666" alt="image" src="https://user-images.githubusercontent.com/1232027/231164302-62b1d44b-0d83-4897-9102-3da190181cda.png">

<img width="261" alt="image" src="https://user-images.githubusercontent.com/1232027/231164360-5301c49d-3fe1-4c39-957f-c95dd0d1b745.png">

A bunch of libraries like [tldts](https://www.npmjs.com/package/tldts) used by millions of projects are using this list by exploding dots in domain suffix and use it as a json object with nested levels as a "group by", using "aéroport" as a json key produce an error causing all those libraries to throw an unexpected error, those kind of characters have nothing to do in a domain name, by the way.

**Comment by dnsguru** [comment]
The suffix in focus of this report is one of many that have been submitted to the PSL over the past 14 years, and this is not a bug.

Please visit the Universal Acceptance Steering Group (UASG) website and encourage those millions of projects to code for the [Internationalized Domain Name (IDN)](https://en.wikipedia.org/wiki/Internationalized_domain_name) standards that have been in place for a few decades.

[Universal Acceptance Steering Group Website](https://uasg.tech/)

The tldts is allegedly IDN compatible, but it looks like perhaps their code choked on their punycode (see: [https://en.wikipedia.org/wiki/Punycode](https://en.wikipedia.org/wiki/Punycode)) xn-- domain conversion or something, but the place to report this issue is to tldts and not here, as there is no bug.

**Comment by dnsguru** [comment]
Just a note, vendors.js was not found in the [tldts project](/remusao/tldts) and they do support IDN.   

Adpating to IDN is encouraged, which means additional considerations for IDNA/Punycode conversions and detection so that errors are not thrown.

It adds a lot of overhead for some projects.  I will caveat the following with it being something I absolutely advise not be done... Although not advised, some coders use the approach of detecting elements that are not [A-z]|[0-9]|-][\.] and skipping them, which works but is a very 1995 approach.

**Comment by Treenity** [comment]
Hi, 

vendor.js is compiled when building a javascript project so you will not found this file in the repository as is.

you can find a copy of the suffix list they use here:
https://github.com/remusao/tldts/blob/master/packages/tldts/src/data/trie.ts

Of course special characters can be integrated in a domain names, nobody usually use them because of multiple problems it can cause, but, as you said, it's allowed and so if CI want to use them, developers need to take care of it.

I will report the problem to the tldts project so they will be able to handle them without causing errors.

thanks for your time

**Comment by remusao** [comment]
Hi, author and maintainer of `tldts` here,

I just stumbled upon this issue and double-checked because it seemed weird to me that the published code would not be valid. In the `tldts` bundles, the `aéroport` string always appears quoted and not as a "naked property" name. For example:

![image](https://github.com/publicsuffix/list/assets/1299873/275f54fe-993a-42da-ad6c-68f0f77a1334)

Is it possible that the issue you encountered above is due to the minifier you use in your project which wrongly removes the quotes around this particular property? (and maybe other properties which should not be allowed to appear without quotes?).

I can also confirm that IDN is supported by `tldts`.

Best,
