### ISSUE TITLE
When will these Google Registry TLDs be imported?

### ISSUE THREAD

**Issue by cicku** [publicsuffix/list#1869]
https://blog.google/products/registry/8-new-top-level-domains-for-dads-grads-tech/

**Comment by cicku** [comment]
Closing, as I was looking at an old version of the file.

**Comment by dnsguru** [comment]
Looks like you sorted out that this was already addressed.

In order to proactively address propogation delay, we use a json file
published by ICANN that is based upon when a TLD goes into contract with
them.

So rather than include the TLD when it is added to the root zone, and then
subsequently wait for browsers to incorporate that change and update, the
contracting has similar certainty with the benefit of advance timing that
might offset delay in propogation.

In the thundering herd from 2012 round, this was more necessary, in order
to have TLDs in the PSL so they are incorporated into software which might
use the PSL through static incorporation in advance of the TLD actually
launching.
