### ISSUE TITLE
Add 3rd party limit examples to template

### ISSUE THREAD

**Issue by simon-friedberger** [publicsuffix/list#1889]
The template currently states:

`__Submitter affirms the following:__ 
\
  * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)`

I have not seen any such claims in the issues I have reviewed so far. If we actually want this information. I think it would be a good idea to add an additional list with some examples as follows:

  * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)`
    - [Cloudflare](https://developers.cloudflare.com/learning-paths/get-started/add-domain-to-cf/add-site/) 
    - [Letsencrypt](https://letsencrypt.org/docs/rate-limits/)
    -  ...add others, remove irrelevant...

**Comment by dnsguru** [comment]
The box is there as 'reasonable friction' so that PSL inclusion is not being requested as a means to bypass third party limits or resistence.  There are large projects that punt people to the PSL in their helper documentation - identifying that inclusion in the PSL is needed for [insert whatever] rather than self-supporting those users.  

IMHO that's a total d%^che a-hole move to shift that burden onto a volunteer-resourced open-source project rather than self-handle at [trillion dollar marketcap largecos], and it is the cause of thousands of lost cycles from this volunteer.  That energy now expressed, I insist I did not add this to be punative.  

It is purely there so that the requestor pauses and has at very least addressed it directly with the third party, and have identified the impacts here.

Truly, it is not really helpful becuase it is all self-assertion - once met with resistence, they review PR that passed and alter their request verbiage to that of the ones that 'isolate cookies' and leave out that the request is actually to bypass third party limits, but they are putting it into the record here.  Removal should be a consequence of lying, intentional omission or misrepresentation on a PR.

> We are listing _any_ third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)`
> * [Cloudflare](https://developers.cloudflare.com/learning-paths/get-started/add-domain-to-cf/add-site/)
> * [Letsencrypt](https://letsencrypt.org/docs/rate-limits/)
> * ...add others, remove irrelevant...

I like that you've enumerated these, please continue and provide a complete list and let's swap it out.

**Comment by simon-friedberger** [comment]
https://support.google.com/adsense/answer/12170421?hl=en from https://github.com/publicsuffix/list/pull/1708
