### ISSUE TITLE
Interest in using go modules

### ISSUE THREAD

**Issue by aaomidi** [publicsuffix/list#1897]
As part of my work on #1894, I noticed that a lot of tooling I have at this point assumes everything uses go modules.

Are there any concerns about adding go modules as part of the generation code?

**Comment by cpu** [comment]
None from me, it's overdue :+1: There were some [discussions](https://github.com/publicsuffix/list/issues/1325#issuecomment-855462155) where the need for it came up before.

I can't remember why it didn't start out as a module. Probably just due to the state of module support at the time the first version was written.

**Comment by weppos** [comment]
> I can't remember why it didn't start out as a module. Probably just due to the state of module support at the time the first version was written.

Yes, most likely this is the scenario. I agree on bringing modules on, as long as they stay confined in the /tools folders and they don't leak outside in the root repo.
