### ISSUE TITLE
[PROPOSAL] Automatically publish as maven artifact

### ISSUE THREAD

**Issue by nielsbasjes** [publicsuffix/list#1925]
Using this list in a project requires periodically updating the file.
It would be really helpful if this file is simply published as a maven artifact in such a way that systems like Dependabot and Renovate can do the updating automatically.

So my proposal is to automate publishing the file as a maven artifact (i.e. a jar file with just this file as a resource with a fixed filename) to maven central.

If that is in place each approved update will automatically publish the new version.

Note that all of this can be automated using GitHub actions and various maven plugins.

Doing the release can be done with the maven release plugin where calculating the next version number can (if needed) be tweaked with something like this https://github.com/nielsbasjes/conventional-commits-maven-release (Yes, I wrote that).

The final artifact can then be publish using this https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

Downstream projects can then simply have a dependency as this which can be automatically updated and simply read the resource file with a fixed name ( '/org/publicsuffix/list.dat' ? ).
```
<dependency>
  <groupId>org.publicsuffix.list</groupId>
  <artifactId>publicsuffix-list</artifactId>
  <version>1.2.3</version>
</dependency>
```

**Comment by simon-friedberger** [comment]
This would be a neat idea but there are a lot of build systems that could be supported and I don't think that is work that this project should be doing. Plus, most build systems support automatic downloading of files for inclusion in a build. Most of them actually support writing arbitrary scripts.

Is there something else that you are trying to solve by creating a maven artifact?

Note, there is also an atom feed with the changes: https://github.com/publicsuffix/list/commits/master.atom

**Comment by nielsbasjes** [comment]
Yes, you can automate a lot with scripting and yes there are too many packaging systems.

Some projects (like https://github.com/apache/httpcomponents-client/blob/master/httpclient5/pom.xml#L125 ) simply download it again and again on each build attempt.

In this personal project I had to write custom code to avoid downloading this file on every build and where I download and commit the file as part of my code repository.
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/code-gen/Antlr/PublicSuffix/UpdatePublicSuffixList.sh

A big reason for me to commit the file myself is that otherwise this makes the software non reproducible. From my perspective the trustworthiness of opensource software can be greatly improved by making all serious projects (like all of the ASF code) reproducible.

See:
- https://reproducible-builds.org/
- https://maven.apache.org/guides/mini/guide-reproducible-builds.html
- https://github.com/jvm-repo-rebuild/reproducible-central
  - https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/nl/basjes/parse/useragent/yauaa/README.md

So either I download and commit the version of the software in my own repo (which I do, and do not like), or I depend on an immutable versioned dependency (like you have in maven central).

From my perspective:
- Maven central is a place where immutable and versioned dependencies can be stored.
- So projects can be made fully reproducible without the need to commit the file locally.
- Many tools are in place that supports this and avoid downloading the updated file needlessly.
- Projects can always revisit an older version of the file.
- This way of publishing the file leaves it open for use by ANY build system and/or language because a jar file published in maven central is simply a .zip file that anyone can unpack.


For me it is fine if a new release is created on each change or just once a day/week/month.
Once a month is good enough for me and would avoid me getting daily updates from renovate to approve.

**Comment by mozfreddyb** [comment]
There are many implementations and packages to make the PSL usable in a variety of languages and ecosystems. We'd prefer not to increase the maintenance burden by adopting support and providing packages for all sorts of downstream usage. The maintenance burden with the current manual process is already cumbersome enough - we have plans to decrease it.

For similar reasons, we do not want to bless any implementation as an "official" one. If your proposed maven artifact is simple to setup, we'd welcome you do it yourself. In fact, we'd be happy to update the homepage and point to your package.

P.S.: I assume you have seen the list of known implementation in Java at to use a maven package instead of the existing usages in Java that https://publicsuffix.org/learn/ lists and decided that those won't work for you.

**Comment by nielsbasjes** [comment]
Understood.

Just to be clear I am not looking for any implementation in any language that uses this data.

I only propose to have an immutably, versioned and thus reliably reusable publication of the actual text file with the official data in a way that makes it widely usable by many projects with their own code implementation. So just a jar file with only the text file that is already in your repo.

If you want to reconsider and if it helps; I'm willing to put up a merge request with what I have in mind.

I checked the Java libraries on that page:
- regdom4j is using a local reinterpretation of the data that has not been updated for 9 years.
- The https://github.com/whois-server-list/public-suffix-list loads the data from your server at every startup (bad idea, won't work in most datacenter setups) and has a last commit of about 8 years ago.
- Guava periodically loads and [commits the data to their own repo](https://github.com/google/guava/commit/2d30e0d6d1776792713d0dde44226e60a81cf2ac) which looks like they have [automated it at their end](https://github.com/search?q=repo%3Agoogle%2Fguava+%22Update+Public+Suffix+data.%22&type=commits).

**Comment by mozfreddyb** [comment]
I understand your proposal and I agree with your assessment that it should be relatively simple. But relatively simple multiplied by every possible package format or language adds up. 
We currently do not intend to version the file. If someone needs to use versioning, I recommend the git commit id. 

My apologies if this sounds harsh or impolite, that's not my intention. I just want to be clear about expectations here.

**Comment by simon-friedberger** [comment]
Is the commit history here not sufficient for these purposes?

**Comment by nielsbasjes** [comment]
Ok, thanks.

**Comment by dnsguru** [comment]
+1 to Freddie's comments
appreciate the suggestion @nielsbasjes 

Update frequency by an integrator / consumer of the PSL is something that is important, due to it not being static.  When the PSL gets used in codebases, often a static snapshot is taken, which can be problematic (see #1807 for example) for user experience when it gets 8-9 years out of sync.  At the opposite end of the spectrum is where frequent updates where a developer pulls from the PSL at each launch of each client - this saturates the bandwidth of the CDN hosting the PSL.

Perhaps your suggestion is in the 'Goldilocks' zone between them...  So I appreciate what you're proposing.

As Freddie mentions, there are a lot of different things that incorporate the PSL - "whole cloth" (as-is), a portion (ex: just ICANN section), or modified versions (where integrator uses some or all of PSL and then adds their own or removes some eTLD+ entries) to factor in to the mix.

We're essentially on our back heels on resources for this project, so adding n+1 additional things to consider in the maintaining of the PSL is something we have to decline - there is already a tremendous amount of tech-debt here so it is unlikely we could onboard it, as it obligates support for others when they point to PSL supporting Maven, which can have a 'Matrioska' of obligations and further volunteer cycle drain.

You are welcome to maintain and operate your own, and we're glad to update documentation to refer to it, as it seems to help with the 'Goldilocks' practice of balanced refresh/burden in positive ways.
