### ISSUE TITLE
c.la

### ISSUE THREAD

**Issue by wdhdev** [publicsuffix/list#2042]
Hi there, I stumbled across `c.la` in the PSL file. I looked at the entry and there is no submitter information [as seen here](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat#L12369-L12370). I looked up the site in my browser and when you go to http://c.la it shows this: 
![image](https://github.com/user-attachments/assets/2f8ef5f9-df0b-43f7-95fb-f412a23aed5b)

In the title bar it says `c.la - This Domain Is For Sale !`. I just wanted to report this as I believe this is against the PSL terms as well as just in case this is a security risk, I couldn't find a PR for it either, so it must've been added before the PSL moved to GitHub.

**Comment by groundcat** [comment]
Indeed, this appears to be an abandoned or terminated service. Based on archive.org, it used to be a subdomain registration service around 2008 (see [archived page here](https://web.archive.org/web/20110728032205/http://c.la/)), but now the domain has been available for sale for some years. 

The website http://www.c.la/ is malfunctioning. 

According to the [archive](https://web.archive.org/web/20110728033607/http://www.c.la/quisommesnous.php), the subdomain service used to be operated by a company in France. Translation:

> The company www1redirectcla, which provides a domain name service in CLA, Sitepersonet, SUPFR, or WEBCVINFO, has its head office located at:
> The River,
> 35440 Dingé,
> France.
> It is registered at Rennes RCS under registration number 480401108.

Per WHOIS, the creation date of the domain is 2004-06-11T01:00:00.0Z, which is before it was repurposed, so I assume this domain was sold and transferred instead of let expired. Now, the registrar is `West263 International Limited` in China, and judging from the information on the "domain for sale" page, the current registrant appears to be in mainland China. 

I checked the certificate transparency reports and found no active SSL certificates in use (for certs that allow CT).

A Google search for "site:c.la" shows no active site except for one "c.la - This Domain Is For Sale!" search result.

Based on the above, I guess it is safe to say that this domain is no longer used for the original purpose and should be removed from the PSL.
