### ISSUE TITLE
Add ICANN spec13 gTLD exceptions

### ISSUE THREAD

**Issue by pzb** [publicsuffix/list#209]
ICANN has developed "specification 13" as an optional amendment to the gTLD registry agreement.  It is described on their site: https://newgtlds.icann.org/en/applicants/agb/base-agreement-contracting/specification-13-applications

It essentially means that the gTLD is effectively a registered domain itself and the public suffix for that specific namespace is basically "" (the empty label).

I propose that all gTLDs with granted specification 13 amendments (as listed on the page above) be added with the PSL with

``` text
example
!example
```

This should (hopefully) cause libraries to do the "right" thing.  I'm not sure how else to encode these domains in the PSL.

**Comment by sleevi** [comment]
Thanks for filing this Peter.

I'm curious what @gerv and @wepoos will thing, but for Chrome, we're opposed to introducing this, and would likely fork the PSL if necessary. We (Chrome, not Google) expressed our concerns to ICANN in the past with respect to brand TLDs and the concerns attached.

It's important to consider how this would behave with respect to the default processing algorithm - which is that the absence of a domain within the PSL indicates that the effective TLD is the top-most label. This would mean that the effective TLD is 'null', which will negatively impact a wide variety of implementations. I know of at least three libraries - including Chrome - at Google which will not do the right thing, precisely because the idea of a 'null' entry is unfathomable.

Similarly, this would result in incompatibilities with (from when I looked at it 6 months ago), every browser's behaviour with regards to cookies.

An alternative is to remove the specification 13 entries from the PSL, since they're not public suffices - which, if that is the argument, will result in the behaviour I described above (the top-most label is still treated as the effective TLD)

**Comment by pzb** [comment]
> the absence of a domain within the PSL indicates that the effective TLD is the top-most label
> [...]
> An alternative is to remove the specification 13 entries from the PSL

I know of at least a couple of libraries which assume that the PSL contains a complete list of all TLDs.  Removing them from the PSL is probably the right solution, but it will probably cause surprising behavior until the libraries are fixed.

**Comment by sleevi** [comment]
Indeed, because we have historically taken the approach that the PSL
contains the entire IANA Root Zone Database.

I don't think there is any good, compatible, or arguably from a browser
perspective, desirable way to accomplish what you want via exceptions.
Introducing a new section or annotation may be possible, but I would argue
it also depends on what you are trying to attempt by signifying Spec13, and
whether that is a useful case for the PSL remains TBD.

**Comment by gerv** [comment]
Peter: Just out of curiosity, why did you not recommend a simple "!example" rule for spec13 TLDs, which seems to me to better encode the intent?

We have asked ICANN to provide a definitive list of which TLDs are spec13 and which are not, and they do plan to do that, in their "newgtlds2.csv" project.

Ryan: the fact that current implementations wouldn't be able to cope with this is a reason why there would be a longer transition period, but is not (in itself) a reason not to attempt to signify this in the PSL. More interesting are your assertions that doing so would be actively harmful, even if implementations understood it. Can you expand on why that is?

**Comment by sleevi** [comment]
Talk to Anne for the Moz details. Our objections are noted with ICANN for
the risks of spec13 and cookies - in particular, how they conflict with how
local, unqualified domains, and the security motivations involved. There is
significant compatibility risk, long term, with what we believe is no
benefit to the security and stability of the platform. You presume the
transition period will end - we do not believe so, and engaging would put
users at risk.

**Comment by pzb** [comment]
The public suffix list is used for more than setting cookie scope.  Notably it is referenced the CA/Browser Forum guidelines and has been suggested to be part of the Chrome CA policy.  So, while I appreciate that cookies are one use the PSL has other uses as well.

I also respect that some part of Chrome expressed concerns to ICANN about specification 13, but I assume Chrome's position has changed as their own `.chrome` gTLD is among those that applied for and was granted spec13.  Additionally Google clearly believes that wildcards for spec13 TLDs are fine as they have issued such in the past and defended them as being OK (https://twitter.com/agl__/status/604100924127117312).

As to @gerv's question about !example, this might work, but the current rules say that `!` only overrides `*`.  This would be a new use of !, unless one considers that there is an implicit `*` rule that is the default.

**Comment by sleevi** [comment]
> but I assume Chrome's position has changed as their own .chrome gTLD is among those that applied for and was granted spec13

No, it has not changed, but whether or not a Spec13 domain exists is independent of our position with respect to how cookies are handled, which, while certainly one of many uses of the PSL, is also the primary.

Wildcards for spec13 TLDs are indeed fine. Cookies for a TLD (effectively), are explicitly not OK. The CA/B Forum Baseline Requirements do not require the modifications you suggest to the PSL - because it specifically, and intentionally, allows a CA to validate the Spec13-ness without having to rely on the PSL. For example, by checking with ICANN the spec-13ness.

**Comment by gerv** [comment]
> As to @gerv's question about !example, this might work, but the current rules say that ! only 
> overrides *. This would be a new use of !, unless one considers that there is an implicit * rule that is 
> the default.

The algorithm spec, step 2, says exactly that:
https://publicsuffix.org/list/

**Comment by gerv** [comment]
I can see how cookies for an entire TLD would be a problematic clash with internal domains - thank you for reminding me of this.

**Comment by dnsguru** [comment]
In speaking with @pzb by phone - this was better related to the Spec 9 (ie. Microsoft has .MICROSOFT as a spec 13 Dot Brand, and .OFFICE is a spec 9 which has exemptions).

Spec 9 defines a namespace that might have a different than normal usage in the wild at some point in the future or internally on nets.  

The TLD can't really be considered the Domain itself.  CA's, Browsers and other usage will need the flexibility to perform the status quo.  We'll close this for now but keep it in the archives for reference.
