### ISSUE TITLE
Instant Messaging for the PSL?

### ISSUE THREAD

**Issue by wdhdev** [publicsuffix/list#2332]
Should we create some form of IM for the Public Suffix List? Maybe something using Discord or Slack? It might be good for smaller issues that don't really require a whole issue on GitHub.

It could also create a form of support channel, which could be useful in some cases, although we already have GitHub issues.

I do recall a Matrix channel however I don't believe anyone uses it, nor really knows about it.

What is everyone's thoughts on this? I think it could be somewhat beneficial.

**Comment by groundcat** [comment]
Why don't we use https://chat.mozilla.org/

**Comment by mozfreddyb** [comment]
@simon-friedberger created a matrix channel, but @dnsguru suggested we don't use it as a source of truth because it's not as open and doesn't allow folks to reference conversations from the past. 

I personally think it's fine as long as we don't use it to communicate decisions and make sure we stick to public artifacts for whenver we make changes & decisions. Simon and I still hang out in https://matrix.to/#/#psl:mozilla.org

**Comment by wdhdev** [comment]
@groundcat I believe chat.mozilla.org is limited to employees of Mozilla as registration for it appears to be disabled.

@mozfreddyb That was the room I was referring to, I wasn't sure if people were actively using it though as I never see messages in there, I've been in it since July. That works however assuming people are at least somewhat active on it haha.

**Comment by mozfreddyb** [comment]
> @groundcat I believe chat.mozilla.org is limited to employees of Mozilla as registration for it appears to be disabled.


I think you can sign in with github?! Maybe that requires org membership? But the server and the channel are public/federated 🤷

**Comment by simon-friedberger** [comment]
(What freddy is saying is, you can make an account on matrix.org and join #psl:mozilla.org.)
