### ISSUE TITLE
Remove Lib.de.us

### ISSUE THREAD

**Issue by ehmoore** [publicsuffix/list#243]
It appears that Chrome will not trust wildcard certificates off of domains listed under ICANN Domains. Lib.de.us is one of these domains. We need to get lib.de.us removed from this list.

**Comment by sleevi** [comment]
Do you want it moved to the private section? Have you considered the
security implications of outright removing it?

**Comment by ehmoore** [comment]
Dear Sleevi,

Thank you for your quick response.  We have had great difficulty getting the Chrome browser to trust wild certificates created by Entrust for our domain.  This issue has dragged for months with the final recommendation from Entrust to remove our name from this list.
Please forgive my ignorance but I am not aware of the security implications behind complete removal and I would certainly appreciate your input on this matter.  It is our belief that being on this list has relegated our wildcard certificates to untrusted within Chrome.
What would be the benefit to just moving our domain listing to private?

Best Regards,

Ed

Edward Moore
Library Technologist
Tel: +1(302) 241 2992
Cel:+1(856) 465-8141
SFB: ed.moore@lib.de.us
ed.moore@lib.de.us<mailto:ed.moore@lib.de.us>

[cid:image002.png@01CF8AEF.6152D8F0]

**Comment by sleevi** [comment]
While it's true that Chrome (and possibly Firefox?) will not respect wildcards for names in the ICANN section (e.g. you don't want a certificate for `*.com` to be used to attack any website), it does allow them in the PRIVATE section.

The biggest security implication to wholesale removal is that anyone would be able to set cookies for `lib.de.us` at that domain level. If subdomains are controlled by separate entities (e.g. `foo.lib.de.us` should not be able to control content at `bar.lib.de.us`), then that represents a security risk, as `foo` could maliciously set a cookie on `lib.de.us` that could allow foo to compromise `bar.lib.de.us`. You can read a bit more about this at https://publicsuffix.org/learn/

It's a question about who controls the content on domains subordinate to `lib.de.us`. If you don't centrally manage all of that content - and allow different parties (e.g. different libraries) to control subdomains - then you likely DO want to be on the public suffix list, so that you can prevent the compromise or malicious use of one subdomain from affecting ALL subdomains. If you centrally host the content (presumably, if you're getting a wildcard certificate, you're directly hosting more than one subdomain), but don't centrally *manage* the content (e.g. you use a CMS or allow libraries to run their own stuff), then adding to the PRIVATE section is probably the right approach. This is more consistent with `lib.de.us` being a bit like a hosting provider - which you can see, a number of hosting providers (Amazon, Appspot, Azure) are in the PRIVATE section for just this reason.

**Comment by ehmoore** [comment]
Dear Sleevi,

Excellent explanation.  Thank you very much.  We are in total control of all websites and subdomains under lib.de.us.  The certificate is required for the library websites.  Per your advice, we would prefer to first move the domain to the private section.  If this works for chrome, then it will suffice.

Best Regards,

Ed

Edward Moore
Library Technologist
Tel: +1(302) 241 2992
Cel:+1(856) 465-8141
SFB: ed.moore@lib.de.us
ed.moore@lib.de.us<mailto:ed.moore@lib.de.us>

[cid:image002.png@01CF8AEF.6152D8F0]

**Comment by sleevi** [comment]
Great. Now we just need to find a way to authorize this request (I know, it's a pain, but helps make sure the right authorizations are in place)

If you can modify lib.de.us to add a TXT record, adding _psl.lib.de.us referencing this issue is sufficient - see https://github.com/publicsuffix/list/wiki/Guidelines

Otherwise, having one of the Administrative/Billing/Technical contacts for lib.de.us is another option - and based on current data, that appears to be Ben Sauselein and George Richard Truitt. Again, this is explained at https://github.com/publicsuffix/list/wiki/Guidelines

Hopefully that makes it easy to vet the request and get the changes in.

**Comment by ehmoore** [comment]
Hi Sleevi,

I will get this done in the morning.  I have copied Ben in this reply.  Thank you for all of your help.

Regards,

Ed

Edward Moore
Library Technologist
Tel: +1(302) 241 2992
Cel:+1(856) 465-8141
SFB: ed.moore@lib.de.us
ed.moore@lib.de.us<mailto:ed.moore@lib.de.us>

[cid:image002.png@01CF8AEF.6152D8F0]

**Comment by ehmoore** [comment]
Sleevi,

Thanks for working with Ed on this issue.  Ed has been in contact with me during all phases of this so far and I have directed him to make the changes requested.

Just so I’m clear on the next steps – we need to add a TXT record to DNS that looks like:   _pls.lib.de.us

Is this correct?

Thanks in advance,
Ben


From: Ed Moore
Sent: Tuesday, June 14, 2016 11:55 PM
To: publicsuffix/list <reply@reply.github.com>; publicsuffix/list <list@noreply.github.com>
Cc: Author <author@noreply.github.com>; Ben Sauselein <Ben.Sauselein@lib.de.us>
Subject: RE: [publicsuffix/list] Remove Lib.de.us (#243)

Hi Sleevi,

I will get this done in the morning.  I have copied Ben in this reply.  Thank you for all of your help.

Regards,

Ed

Edward Moore
Library Technologist
Tel: +1(302) 241 2992
Cel:+1(856) 465-8141
SFB: ed.moore@lib.de.us<mailto:ed.moore@lib.de.us>
ed.moore@lib.de.us<mailto:ed.moore@lib.de.us>

[cid:image002.png@01CF8AEF.6152D8F0]

**Comment by sleevi** [comment]
If you can either authenticate this request by sending an email to team@publicsuffix.org from an email address listed on the WHOIS, or, ideally, adding a TXT record of _psl.lib.de.us that contains the URL for this issue, as explained on https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by sleevi** [comment]
Validated out-of-band using WHOIS information on the domain. If @weppos or @gerv isn't able to get to it before, I should be able to get to this on Monday.

**Comment by weppos** [comment]
I apologize for the delay. I must admit I was not actively following the conversation, and I've just noticed today that I was pinged by @sleevi 

I opened https://github.com/publicsuffix/list/pull/256

I have only one concern here: @ehmoore are you aware that other consumers of the PSL may interpret the rule differently? For example, there are some consumers that uses the list of suffixes in the ICANN section to grant special permissions, here's an example https://github.com/letsencrypt/boulder/blob/master/policy/pa.go#L290-L313

To be clear, I'm not discouraging @sleevi suggestion. I'm just making sure you are fully aware of potential issues in the future.
