### ISSUE TITLE
us TLD missing lots of public suffixes

### ISSUE THREAD

**Issue by pzb** [publicsuffix/list#274]
The .US zone file shows there are 2391 public suffixes.  Many of these are in the form of <city>.<state>.us.

The full list, as of 2016-08-06, is at https://gist.github.com/pzb/e7ff42324856b0bc13779ac8067d8dcd

**Comment by sleevi** [comment]
Would you be willing to submit a pull request?

**Comment by dnsguru** [comment]
Closing 

This was tied to the closed PR #276 which was enormous and did not get implemented due to size.  @pzb thank you for taking the time to curate and thoughtfully submit this.  I created #981 to consider some means to address some of the radically detailed subspace like this, but we opt to wontfix for now and continue to document these.
