### ISSUE TITLE
Host the site on GitHub

### ISSUE THREAD

**Issue by annevk** [publicsuffix/list#28]
Makes it easier to fix small bugs, such as the lack of HTTPS in the link to Mozilla Foundation. And add new standards that depend on this mechanism, such as https://storage.spec.whatwg.org/ (not explicit yet, see #27).

**Comment by weppos** [comment]
@gerv I'm not aware of the implications of moving the site repo to GitHub, and publish it via deploys. Is it something we can consider? That will definitely help the maintenance.

To be clear, I don't think we can move the site to GitHub Pages because of the following blocking requirements:

- [The list mirror](https://publicsuffix.org/list/public_suffix_list.dat)
- HTTPS (GitHub pages don't support it)

However, migrating from the current repo to one here on GitHub would definitely be helpful. I honestly have no idea where the repo is, nor how to deploy changes to production.

**Comment by annevk** [comment]
The way we deploy most of the WHATWG standards is by having a push-hook that pings a script on the server that pulls the latest from GitHub and deploys it. I somewhat prefer that over GitHub Pages since it keeps the essentials not tightly coupled to GitHub.

**Comment by gerv** [comment]
Currently, the website is in Mozilla SVN. I'm not sure the level of change warrants the effort of moving to a new hoster. I've fixed the mozilla.org links to be HTTPS.

**Comment by annevk** [comment]
It would make it easier to contribute. E.g., there's another open issue about the "Formal Algorithm" that I'd like to see resolved. I was thinking that maybe providing a PR would help things along there, but currently I can't really do that.

Having to do that against Mozilla SVN would be a bit more of a pain, but currently that isn't really documented to begin with.

**Comment by gerv** [comment]
The site is static; just save the HTML file to disk and send me a diff. If the rate of change starts to get high, I'll ponder a hosting change.

Gerv

**Comment by annevk** [comment]
I think you're missing the point. By not making it part of the project the changes to it are not very transparent or up for inspection. And given that it does define an implementation algorithm that kind of transparency is important.

**Comment by weppos** [comment]
@gerv I'd like to make a few changes to the site. For example, I'd like to add a link to the [Go library](https://github.com/weppos/publicsuffix-go) I built, or try to clarify #208 or update the site to link to the Guidelines.

Needless to say, having it on this organization here on GitHub would help. However, I understand the complexity of drastically changing the current state.

Let me propose you an intermediate agreement. GitHub supports SVN. Each Git repo can be exposed via Subversion.
https://help.github.com/articles/support-for-subversion-clients/

What about migrating the site repo to GitHub, and simply update the tool that performs the deploy to use the GitHub SVN URI, rather than the current repo? Do you think it could be a viable solution?

**Comment by gerv** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1267268 filed to get the Webops team to look into this.

Gerv

**Comment by gerv** [comment]
https://github.com/publicsuffix/publicsuffix.org is now the master repo for the website. :-)

Gerv

**Comment by annevk** [comment]
Thank you, that is great!

**Comment by weppos** [comment]
That's awesome! Thanks Gerv.

On Thursday, 5 May 2016, Anne van Kesteren <notifications@github.com> wrote:

> Thank you, that is great!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/publicsuffix/list/issues/28#issuecomment-217160731>
>


-- 
Simone Carletti
Passionate programmer and dive instructor

https://simonecarletti.com/
Twitter: @weppos <https://twitter.com/weppos>

**Comment by gerv** [comment]
weppos: feel free to submit PRs for the issues in your comment above.

Gerv
