### ISSUE TITLE
s3.amazonaws.com is not a valid publicsuffix

### ISSUE THREAD

**Issue by piazzamp** [publicsuffix/list#303]
since https://s3.amazonaws.com/somtehing/whatever.html is a valid URL, then s3.amazonaws.com shouldn't be a valid publicsuffix right? or is my understanding of the definition of publicsuffix incomplete?

**Comment by sleevi** [comment]
@piazzamp Could you expand what you mean by "valid URL"? Amazon certainly has requested `s3.amazonaws.com` be added. The https://s3.amazonaws.com/something/whatever.html form is less secure (because no same-origin protection), so I don't believe it should be recommended.

In any event, because `bucket.s3.amazonaws.com` is also valid, adding it to the PSL is the safer bet, as is done.

**Comment by piazzamp** [comment]
sorry I had an incomplete view of the uses of this list
