### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by dago** [publicsuffix/list#31]
Hi,

it would be easier for downstream packagers if there were release tarballs.

Best regards -- Dago

**Comment by sleevi** [comment]
Why are you packaging it? It should be expected to be updated several times a week, and for efficiency, should be precompiled/preprocessed.

**Comment by yaneti** [comment]
That wasn't directed at me but as the one that tries to do the publicsuffix list packaging for Fedora I'll try to share my thinking in broad terms:
- a properly engineered system shouldn't have N (possibly differing) copies of the same data
- any startup preprocessing costs would be insignificant compared to the lifetime for the majority of the programs/utilities that might have a use for the list.

**Comment by rockdaboot** [comment]
@yaneti There is a library having the data precompiled (and tested) plus functions for easy checks / access: https://github.com/rockdaboot/libpsl
Wget is already using it. It guess I have to patch a few other clients as well...

ACK regarding PR #21. It also breaks Travis-CI testing for libpsl since a while.

**Comment by dago** [comment]
Basically because everything going to a client machine needs to be packaged :-)

**Comment by weppos** [comment]
@dago since this is not a library, rather a definition file, I can't really understand how a package would be helpful. I expect this definition file to be downloaded and packaged along with a library that uses it, rather being distributed as a standalone package.

Can you provide me a real world example of where a package of this definition would be useful? Also, did you start this proposal because of a specific need or issue you experienced? Can you provide more context?

**Comment by dago** [comment]
When compiling `libpsl` the `public_suffix_list.dat` is needed. Currently I implemented it by packaging the public suffix list with a timestamp as version and make it a compile time dependency to libpsl. Our build system pulls in build time dependencies automatically when these are packages. This looks cleaner to me than shoving it all in the libpsl build recipe.

**Comment by sleevi** [comment]
@dago Given that you have version control, it seems far better to use the git hash as the version (as done by Chromium, when packaging)

But this definitely sounds like something better suited for libpsl packaging; you can see every git version as 'a release' and thus worthy of updating. There's no particular purpose served by adding a numeric value to every release, and there's no symbolic difference between any two commits.

**Comment by weppos** [comment]
I'm closing this for now, as it seems releasing packaged versions of the list is unfeasible for us, due to the very frequent changes. The list should probably be packaged in the various library versions, and/or libraries should provide a way to load an arbitrary list (AFAIK libpsl does it) if the dev wants to pin to a specific PSL version.

I'd encourage the use of git SHAs for pinning specific list versions.

/cc @sleevi @gerv
