### ISSUE TITLE
Add wildcard DNS: xip.io, nip.io

### ISSUE THREAD

**Issue by juju4** [publicsuffix/list#335]
simple wildcard DNS for any IP Address

http://xip.io/
http://nip.io/

> NIP.IO allows you to map any IP Address in the following DNS wildcard entries:
> 10.0.0.1.nip.io maps to 10.0.0.1
> app.10.0.0.1.nip.io maps to 10.0.0.1
> customer1.app.10.0.0.1.nip.io maps to 10.0.0.1
> customer2.app.10.0.0.1.nip.io maps to 10.0.0.1
> otherapp.10.0.0.1.nip.io maps to 10.0.0.1
> NIP.IO maps <anything>.<IP Address>.nip.io to the corresponding <IP Address>, even 127.0.0.1.nip.io maps to 127.0.0.1 

Affects letsencrypt rate-limit.

**Comment by weppos** [comment]
Please read https://letsencrypt.org/docs/rate-limits/, it contains a form to request higher limits.

**Comment by sleevi** [comment]
Additionally, no browser supports the syntax you've described, meaning it is impossible to do what you want securely (that is, without sharing cookies and other permissions)

**Comment by juju4** [comment]
Hello @weppos, @sleevi 

I'm not the owner of those domains, just a user. Those domains are similar in usage as no-ip.net, ddns.net. Like those, I'm not sure where limits should be address but it seems no-ip was done at public list level that's why I open the issue.
I quickly checked the form and it is targeted to domain owner/organization.

the syntax is working without issue. It map *any IP address* (IPv4 only, I believe), public or private.
for testing, it's an easy way to get a domain without having any other action to do, for example on a vps install.
it's pure dns and as such, no change of browser or clearly no cookie is involved. It can affect service for http HOST header clearly but that's it.

Last, I can't explain limits as https://crt.sh/?q=nip.io returns nothing and I did a few tests this week (but no more than 5)

If you still think, it's better to request higher limit, just say so and will try that road.

**Comment by sleevi** [comment]
I'm afraid you confused my remarks about browser security with technical syntax. While it resolves, no browser will allow you to protect those domains from hostile or malicious content - it is insecure by design. The PSL helps provides hints to browsers on how to secure domains, but neither the PSL nor browsers support any form of syntax to allow those domains to be used safely. It is defective, even if you can get browsers to connect.

As for the second half, the PSL is not for getting around LE rate limits. Further, just like LE's limits require the domain holder to fill the form, additions to the PSL require the domain holder to request them. If the domain holder did, we would explain to them how the PSL does not support their use case, and thus would not be appropriate for inclusion.

We appreciate you filing this issue, as these policies may not have been obvious (though we try to spell it out on publicsuffix.org and on the wiki). If you are a xip.io/nip.io customer, your safest and most secure option would be to stop using their services. Best of luck!
