### ISSUE TITLE
Add .za TLD

### ISSUE THREAD

**Issue by random-guy** [publicsuffix/list#390]
Hello,

.za TLD is not present in the current list.

There several SLD which use .za TLD:
ac.za
agric.za
alt.za
co.za
edu.za
gov.za

but the TLD itself is not present.

Can you add it?

**Comment by weppos** [comment]
There is a section for the ZA suffix:
https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat#L6794

The `za` itself is not present because it's not an allowed suffix (at least that's what we know until now). Do you have any evidence that za is a valid suffix?

Please make sure to be familiar with the PSL project and format, as it seems to me that your requests is based on a specific need to have .ZA listed, whereas this is not the case unless .ZA is a valid suffix.
