### ISSUE TITLE
Q: PSL to be applied to HPKP and HSTS ?

### ISSUE THREAD

**Issue by rockdaboot** [publicsuffix/list#403]
I am looking for clarification...
HPKP and HSTS headers (similar as Set-Cookie) have a flag 'includeSubDomain'.
It seems reasonable to check the domain against the PSL if that flag is set. Else e.g. with HPKP a  domain could set PINs for unrelated subdomains, the subdomains would be no longer available to that client.
I think that similar concerns apply wherever a domain claims to have authority of subdomains !?

Am I wrong ?

**Comment by sleevi** [comment]
The specs don't require it, and elsewhere - whether for effective TLDs with
a shared hosting structure or for new gTLDs - it's desirable to let it be
set.

What do you see as the PSL issue? Implementations would need to behave as
you suggest to be a documentation matter for the PSL, so not sure any
action is required?

**Comment by rockdaboot** [comment]
Sorry, this was meant as "Question" (I couldn't label the issue appropriate).

After having more time to think: HSTS and HPKP 'includeSubDomain' settings should be protected/checked by/against the PSL.
I'm going to patch wget/wget2 (and maybe curl later) and inform https://publicsuffix.org/ about new uses (guess through psl-discuss mailing list is best !?).

**Comment by sleevi** [comment]
@rockdaboot That's a check that doesn't match what Firefox/Chrome/Safari have deployed. For at least HPKP, we (the spec authors) _didn't_ want that interpretation. And we have some TLDs trying to go on the HSTS preload list (notably, `.gov` wants to be)

That said, you're free to apply those checks, just know that it's likely going to be a divergent implementation :)

**Comment by rockdaboot** [comment]
@sleevi Maybe you know *how* browser do address that issue (includeSubDomains) for HPKP, of course I would like to stay as close to browser implementations as possible.

If you explicitly didn't want PSL applied for RFC7469, you forgot to mention that in the RFC.

Is there a different list like the PSL, just for HPKP and/or HSTS ?

Just an example:
Imagine dyndns.org sends (accidentally) pubkey pins with includeSubDomains=1. Now that is for max-age seconds in my HPKP cache. It doesn't allow me to visit any subdomains (these belong customers with their own certificates) during that period (that I don't already have in HPKP cache). Without manually removing these entries I am stuck.
How do browsers protect against that ?

**Comment by sleevi** [comment]
On Wed, Feb 22, 2017 at 2:58 AM Tim Rühsen <notifications@github.com> wrote:

> @sleevi <https://github.com/sleevi> Maybe you know *how* browser do
> address that issue (includeSubDomains) for HPKP, of course I would like to
> stay as close to browser implementations as possible.
>

No rules/limits. That is, .com could pin for all of .com, .secure can pin
for all of .secure, and .google can pin for all of Google (the latter does
happen, via the preload list, and applies to all subdomains). Similarly, if
.gov wants to force HSTS, it can.

The only practical limits on this are the ICANN gTLD or IANA Delegation
contracts that prevent a bare host record on a TLD, thereby preventing it
from dynamically being applied (but permitting it via preload)

If you explicitly didn't want PSL applied for RFC7469, you forgot to
> mention that in the RFC.
>

Conversely, if it was a necessary or intended property, we would have
spec'd it :)

Is there a different list like the PSL, just for HPKP and/or HSTS ?
>
> Just an example:
> Imagine dyndns.org sends (accidentally) pubkey pins with
> includeSubDomains=1. Now that is for max-age seconds in my HPKP cache. It
> doesn't allow me to visit any subdomains (these belong customers with their
> own certificates) during that period (that I don't already have in HPKP
> cache). Without manually removing these entries I am stuck.
> How do browsers protect against that ?
>

They (intentionally) don't, because dyndns.org - or appspot.com - are
totally authorized and capable of setting their policies for their
subdomains. The subdomains do not "belong" to their customer (in that great
ICANN debate on whether names are properties), they remain that of the
domain holder.

Indeed, if github.io wants to force HSTS or HPkP (Since GitHub always
hosts), you arguably *want* that, so a single observation can protect all
GitHub domains (in the dynamic case)

>

**Comment by rockdaboot** [comment]
I think I got it now, thank you for taking the time.
