### ISSUE TITLE
Static CSV and JSON

### ISSUE THREAD

**Issue by indolering** [publicsuffix/list#445]
Would it be possible to add a static CSV and JSON file to the build?

**Comment by sleevi** [comment]
Why? They can be generated from the existing dat file, and that way
consumers can have a single authoritative file.

**Comment by weppos** [comment]
Hi @indolering, as anticipated by @sleevi, we decided to not generate extra formats to leave the freedom to convert the main authoritative file into any user-specific formats.

Providing a CSV or JSON or any other extra format would increase maintenance complexity, and would not really be of any help because users may want different encoding or structures for JSON key names, for example.
