### ISSUE TITLE
Remove taxi.aero and marketplace.aero

### ISSUE THREAD

**Issue by aero-enquiries** [publicsuffix/list#51]
SITA (sponsor of the .aero TLD) would like to remove these two domains from the list:

taxi.aero
marketplace.aero

Regards,
SITA .aero office

**Comment by weppos** [comment]
Hello, thanks for your submission. As this is the first submission from this user, we need to validate the affiliation with the .AERO TLD.

Do you have an email we can reach you out to validate your request, or do you mind to send us an email at submissions@publicsuffix.org from an email address associated with the .AERO TLD so that we can validate this account?

Once validated we'll go ahead and apply the changes.

**Comment by aero-enquiries** [comment]
Hello,

This github account is associated with the admin e-mail of the .aero TLD. We will also send a separate e-mail from that address for validation.

Thanks
SITA .aero office

**Comment by aero-enquiries** [comment]
The e-mail address you mentioned is not working:

550 5.1.1 <submissions@publicsuffix.org>: Recipient address rejected: User unknown in virtual alias table

**Comment by gerv** [comment]
Sorry. Please use "team" at the same domain. Thanks!

Gerv

**Comment by weppos** [comment]
Merged, thank you.

/cc @gerv

**Comment by weppos** [comment]
@sleevi I was asked how often Google Chrome pulls the changes. Do you happen to know such information?

**Comment by sleevi** [comment]
@weppos random bug for the discussion, but 12-18 weeks is the upper bound.
