### ISSUE TITLE
Please add TLD co.cz to the list

### ISSUE THREAD

**Issue by Artiemr** [publicsuffix/list#52]

**Comment by weppos** [comment]
Hello @Artiemr, I investigated about the .co.cz suffix and as far as I understood it's not an official suffix provided by the .CZ registry, but it's a private suffix managed by http://www.i-registry.cz/index.php?option=com_content&view=article&id=47&Itemid=53&lang=en

Are you affiliated with them? As per out policy, we can only include the `.co.cz` suffix if the entity behind the service will request it.

**Comment by Artiemr** [comment]
Hello, yes .co.cz is not official suffix, but many DNS providers support it. Unfortunately I am not the administrator of this service. I would like to download your list with this suffix, because our system for customers makes it possible.

**Comment by msemrad** [comment]
Hello, I'm administrator of .co.cz. I wanna include .co.cz suffix to the list. Is sufficient only this authorization?

**Comment by weppos** [comment]
Hello @msemrad, in order to validate your account, can you please send an email to team at publicsuffix dot org from an email that is clearly associated with .co.cz and from which we can validate the authorization to add the suffix.

Do you confirm that my assumpio that the suffix is managed by http://www.i-registry.cz is correct?

**Comment by msemrad** [comment]
Hello,

I can't send email directly from .co.cz because our company uses 
@i-registry.cz as primary email domain.

I confirm that the suffix is managed by www.i-registry.cz

You can chceck it thru whois:

%  (c) 2006-2015 CZ.NIC, z.s.p.o.
%
% Intended use of supplied data and information
%
% Data contained in the domain name register, as well as information
% supplied through public information services of CZ.NIC association,
% are appointed only for purposes connected with Internet network
% administration and operation, or for the purpose of legal or other
% similar proceedings, in process as regards a matter connected
% particularly with holding and using a concrete domain name.
%
% Full text available at:
% http://www.nic.cz/page/306/intended-use-of-supplied-data-and-information/
%
% See also a search service at http://www.nic.cz/whois/
%
%
% Whoisd Server Version: 3.10.0
% Timestamp: Sat Nov 28 18:12:33 2015

domain:       co.cz
registrant:   I-REGISTRY
nsset:        NSS:IREGISTRY:1
keyset:       KS:CO.CZ:1
registrar:    REG-GENREG
registered:   26.03.2002 12:59:00
changed:      11.12.2008 09:12:15
expire:       25.03.2018

contact:      I-REGISTRY
org:          i-registry s.r.o.
name:         Martin Semrad
address:      Nad vĂ˝pustĂ­ 142
address:      Praha 4
address:      14900
address:      CZ
registrar:    REG-GENREG
created:      28.08.2008 14:03:00

nsset:        NSS:IREGISTRY:1
nserver:      ns1.i-registry.cz
nserver:      ns.i-registry.net
tech-c:       I-REGISTRY
registrar:    REG-GENREG
created:      11.12.2008 09:06:07
changed:      29.08.2011 17:03:12

keyset:       KS:CO.CZ:1
dnskey:       257 3 5 
AwEAAZVZpJMXSnhQ1WPIBcNEKJo2wSwn5RJBS6t5Wbaguis/KeE36ylB9o 
 
 
 
Fm4y1P3ApL+so1KR63IZI6etq1T2kYTnc/Ci7BsnHwjkTN2bYSNJ1pHwjBVhIGrXycBVpb2XuTarZrlf 
 
 
 
7ttr4dtXbfKDNkGpxBteAT23s44M6cdqSxlfK2JaLnn+B6lvXyCME8iG00SKFDIbELo+GAeANvekNs7Y 
 
 
 
OOMJ3mZbhstLkpaTveWJOHNK+iHq+z4GJ4g8PKJMPpW3mrSfd6FairxpP45iHcunpmljKnU+E3xYkSe0 
 
 
 
Dpsn4DNsiONgiMojGMCVZe/hqylh6HkjcKC5m7lDUbCIUvjUjW6aDAuBKSvIJmTNhnKmKWicmGWSL5DB 
 
 
 
wDGqtosEbeMwUi1NXUbUdm2eOJT7vCxRDPdpqNRUljhv2IAX/eHvsahWFReP9MKkWl+fsynoPez9uxF8 
 
 
 
koFLPILU4Eh3ea/1ONxdJAIHeF47wfT3fXlM/7sTb3V2wPOHkeddK0ridrIFN7uXP/OxLqNg02BJ5jsI 
 
 
 
a07knEG001CptxF7aBpT+aB87JdtM+QD//FhehM4zGmfQODM6swAncOOteReEwMr4/pw520qMJoG0TO8 
 
 
 
mO9LJvwUm4piBh3RwJRhk2x6O0MaN3Gj2QcVvt67iCG9zfxyInbfULWVNsPf/DfMBcaYQd
tech-c:       MARTIN.SEMRAD
registrar:    REG-GENREG
created:      29.10.2008 09:18:15
changed:      12.07.2012 17:11:52

contact:      MARTIN.SEMRAD
name:         Martin Semrad
address:      Nad vĂ˝pusti 142
address:      Praha 4
address:      149 00
address:      CZ
registrar:    REG-GRANSY
created:      29.10.2008 09:18:01

Best regards,

Martin SEMRAD
i-registry s.r.o.
e-mail: semrad@i-registry.cz
tel: +420.246083380

Dne 26.11.2015 v 15:59 Simone Carletti napsal(a):

**Comment by weppos** [comment]
@msemrad I sent you an email

**Comment by weppos** [comment]
@msemrad I created a patch. Can you please confirm it? 
See https://github.com/publicsuffix/list/pull/111
