### ISSUE TITLE
What is order of merging pull-requests?

### ISSUE THREAD

**Issue by mattn** [publicsuffix/list#638]
Sorry. I don't have strong opinion but it seems that some older pull-requests are not merged even though newer pull-request was merged. And the older pull-requests seems not have problems. What is order of merging them?

**Comment by weppos** [comment]
There is no formal or specific order, as not all the requests have the same priority.

As a maintainers, we focus on what is best for the stability and long-term vision of the project.

Shorter PRs, PRs updating/removing existing entries, and PRs submitted by trusted teams may get reviewed and merged before simply because of the level of effort.

PRs or issues regarding IANA TLDs have generally the highest priority at all.

Again, this is just an example, not a formal process definition.

**Comment by mattn** [comment]
@weppos  Thanks your answer. Please answer one more question. Could you please look this?

https://community.letsencrypt.org/t/limitation-of-jp-tld-suffix/53063

Currently, .jp TLD is restricted as being bundled one domain for let's encrypt. So we can't get SSL at most of DDNS service in japan. I recognize this as a big problem. mydns.jp is famous service in japan. And the pull-request is filed in #610 . Is this a low priority for you?

**Comment by weppos** [comment]
I do not have low priorities, I'd rather consider _standard_ or _high_ priorities. This is a _standard_ priority for me.

On top of that:

1. That request does not comply with our guidelines https://github.com/publicsuffix/list/wiki/Guidelines
2. As this is a request targeting LE, it should go to their rate limiting form: https://goo.gl/forms/plqRgFVnZbdGhE9n1

> If you are a large hosting provider or organization working on a Let’s Encrypt integration, we have a rate limiting form that can be used to request a higher rate limit. It takes a few weeks to process requests, so this form is not suitable if you just need to reset a rate limit faster than it resets on its own.
