### ISSUE TITLE
wroclaw.pl is a domain no longer a suffix

### ISSUE THREAD

**Issue by liliaouldhocine** [publicsuffix/list#646]
Hi guys, 

I was validating client domains, and weirdly https://www.wroclaw.pl/ was not passing. 
So i went into the tldjs library and noticed that they are basing their validation on the public suffix list. 

Can you please update the list and remove my client domain from it? 

Thanks

**Comment by weppos** [comment]
Partially related to #146

**Comment by liliaouldhocine** [comment]
@weppos is there missing informations to make this go forward?

**Comment by simon-friedberger** [comment]
https://www.dns.pl/en/list_of_regional_domain_names lists wroclaw.pl as a regional domain.

I ran a quick diff between the domains listed there combined with https://www.dns.pl/en/list_of_functional_domain_names and the PSL and the result is basically that `.gov` is missing on the website but that might just be because it is not available to the public.

```
@@ -1,3 +1,4 @@
+pl
 agro.pl
 aid.pl
 atm.pl
@@ -26,6 +27,62 @@
 gmina.pl
 gniezno.pl
 gorlice.pl
+gov.pl
+ap.gov.pl
+griw.gov.pl
+ic.gov.pl
+is.gov.pl
+kmpsp.gov.pl
+konsulat.gov.pl
+kppsp.gov.pl
+kwp.gov.pl
+kwpsp.gov.pl
+mup.gov.pl
+mw.gov.pl
+oia.gov.pl
+oirm.gov.pl
+oke.gov.pl
+oow.gov.pl
+oschr.gov.pl
+oum.gov.pl
+pa.gov.pl
+pinb.gov.pl
+piw.gov.pl
+po.gov.pl
+pr.gov.pl
+psp.gov.pl
+psse.gov.pl
+pup.gov.pl
+rzgw.gov.pl
+sa.gov.pl
+sdn.gov.pl
+sko.gov.pl
+so.gov.pl
+sr.gov.pl
+starostwo.gov.pl
+ug.gov.pl
+ugim.gov.pl
+um.gov.pl
+umig.gov.pl
+upow.gov.pl
+uppo.gov.pl
+us.gov.pl
+uw.gov.pl
+uzs.gov.pl
+wif.gov.pl
+wiih.gov.pl
+winb.gov.pl
+wios.gov.pl
+witd.gov.pl
+wiw.gov.pl
+wkz.gov.pl
+wsa.gov.pl
+wskr.gov.pl
+wsse.gov.pl
+wuoz.gov.pl
+wzmiuw.gov.pl
+zp.gov.pl
+zpisdn.gov.pl
 grajewo.pl
 gsm.pl
 ilawa.pl
```

In any case, it seems this should stay on the list.
