### ISSUE TITLE
NIC EL SALVADOR

### ISSUE THREAD

**Issue by RegistryPRO** [publicsuffix/list#666]
@frju365  I would like to ask only one question that I did not find in the Guidelines.

This doubt came project NIC EL SALVADOR.

The suffix is reserved, but only I can remove the constraint, but it will still be released.

To request a PR, should I remove the restriction from the domain and soon after creating a site with the rules and a PR?

The staff has a person who speaks English in an intermediate and fluent Spanish.

**Comment by RegistryPRO** [comment]
Example%

Reason of this Pull Request

NIC EL SALVADOR is a servir operating DNS system aiming to make self-hosting accessible to everyone.
We provide subdomain el.salvador.br to our users, allowing them to self-host some services without the need of buying a personnal domain and with the advantage to bypass some ISPs dynamic IP and to configure DNS entries automatically.

It could be very usefull, if browser could correctly manage those subdomains (cookies, highlighting the subdomain, sorting by subdomain and not all the domain ). We want these services to be recognized as a known public suffix and registro.br, Super DNS and VPSBR services too.

Dig request output

dig +short TXT _psl.el.salvador.br "https://github.com/publicsuffix/list/pull/666" 


Extra info

I am a member of the NIC EL SALVADOR council (the decision-making body of the NIC EL SALVADOR project). I have been mandated by the NIC EL SALVADOR COUNCIL. 
To open this PR with the "submitted by Saymon Rhuano " instead of "submitted by NIC EL SALVADOR " as you requested it. I have put the security [at] NIC.EL.SALVADOR.BRmailing list as email contact (more appropriate) but if you want insist I can edit this PR with the personnal saymonrhuano[at] Gmail.com instead.

I am also known as ljf inside the NIC EL SALVADOR community. I have made the PR directly from a fork hosted on our official organization on github.

**Comment by RegistryPRO** [comment]
Note: This is only a non-real example.

**Comment by frju365** [comment]
Well... I don't know... but I think you must have a website, just to legitimate the orga/person who makes the PR.

Normally, an orga ask the PSL to add his domain, because this orga has a problem and need to add the domain because of problem of security, or cookie... as you explained in the example. But ofc, having a website is normal, because we need the proof that users uses your domain.

If you don't want to release the domain now, it's not a problem... as we have TXT record and a legitimation of the orga. At least it's my point of view (if I understood your question). The website have to be here already. 

What @sleevi and @weppos meant, is that the PSL is not a game, but need to solve real problems (I'm sure that you already understood), and so, we know to know clearly the problems. It's the MOST important.

**Comment by RegistryPRO** [comment]
.
