### ISSUE TITLE
.cy (cyprus) ccTLD 2nd level domains

### ISSUE THREAD

**Issue by hserus1477** [publicsuffix/list#7]
Hi - you currently just have 

// cy : http://en.wikipedia.org/wiki/.cy
*.cy

However there are multiple 2nd level domains here.  

I am NOT affiliated with the cyprus ccTLD. However this is right off their website.

http://www.nic.cy/nslookup/online_database.htm
The dropdown shows you - 

com.cy
biz.cy
ltd.cy
pro.cy
net.cy
org.cy
name.cy
tm.cy
ac.cy
ekloges.cy
press.cy
parliament.cy

Here's a screenshot

![image](https://cloud.githubusercontent.com/assets/13009456/8296912/2db2d972-1974-11e5-9e2c-22d617efd88e.png)

**Comment by weppos** [comment]
Hi @hserus1477, thanks for your patch. `*.cy` means that the domain is only allowing one-level suffixes, therefore it's mostly equivalent with listing all the suffixes.

However, I believe we were trying to switch from generic definitions to explicit definitions because of a preference from Google Chrome guys, therefore the patch may probably make sense.

@gerv @sleevi do you confirm that an explicit list is preferable instead of a generic wildcard in this case?

**Comment by sleevi** [comment]
Personally, I've preferred the wildcard, but Peter Kasting preferred the more explicit form.

The argument for the explicit form is:
1. If the ccTLD ever wishes to allow first level registrations, then having a wildcard policy prohibits them from doing so until all consumers of the PSL are updated
2. With Chrome's policy of using the PSL for determining whether to search vs navigate, having a *.ccTLD means that if a user types a.baz.ccTLD when they meant a.bar.ccTLD, we'll attempt a navigation (because we treat baz.ccTLD as a valid ccTLD), the user will get an NXDOMAIN page, rather than our default behaviour, which would be to execute a search.

The second issue is less important (and we're more fluid to change), and with our rewritten public suffix implementation, we can efficiently handle many explicit enumerations. However, implementations such as Firefox (which use a hash solution, similar as Chrome used to), many explicit entries may be worse for performance for them.

So to directly answer your question: A weak preference for a more explicit listing.

**Comment by dnsguru** [comment]
The request from chrome is not alone; The explicit listing is also desired from many of the third party integrators and developers where possible, such as for anti-spam or form / data entry validation in sofware libraries.  The more pedantic the detail, the better.

**Comment by hserus1477** [comment]
For me at least the advantage of checking for say foo.com.tld which exists versus foo.fake.tld where there isn't any 2ld called fake.tld, comes in fairly useful.  Thanks for looking into this.

--srs

**Comment by hserus1477** [comment]
I see Jothan made the same point I wanted to make .. Thanks, and nice to see you here as well :)

--srs

**Comment by weppos** [comment]
Thanks all for your feedback, I'll make sure to validate and merge the changes asap.

**Comment by gerv** [comment]
The list in the first comment is incomplete, at least according to Wikipedia. gov.cy is missing. We need to be really careful when expanding asterisks that we get all the options.

Is there a way to ask the DNS to give us a full list? I seem to remember that often DNS servers don't let you download an entire zone...

Gerv

**Comment by hserus1477** [comment]
Er - I got the list from the website of nic.cy which administers the cy ccTLD.  That'd be what Wikipedia calls a primary source, in this case.

--srs

**Comment by gerv** [comment]
hserus1477: yes, they are a primary source, but they don't guarantee that the list on that web page you give is complete. .gov.cy is probably not on there because it's not possible for a random person to register one. You have to be careful about repurposing information sources for things other than their original purpose :-)
