### ISSUE TITLE
Some well formed base domains fail to check

### ISSUE THREAD

**Issue by pshevtsov** [publicsuffix/list#91]
I'm running the [following test case](https://github.com/pshevtsov/publicsuffix-list/blob/well-formed-base-domains/tests/test_psl.txt) with `libpsl`:

```
checkPublicSuffix('amber.museum', 'amber.museum');
checkPublicSuffix('aip.ee', 'aip.ee');
checkPublicSuffix('africa.com', 'africa.com');
checkPublicSuffix('amursk.ru', 'amursk.ru');
checkPublicSuffix('appspot.com', 'appspot.com');
checkPublicSuffix('ar.com', 'ar.com');
checkPublicSuffix('eu.org', 'eu.org');
checkPublicSuffix('nsk.ru', 'nsk.ru');
```

and it fails:

```
psl_registrable_domain(amber.museum)=NULL (expected amber.museum)
psl_registrable_domain(aip.ee)=NULL (expected aip.ee)
psl_registrable_domain(africa.com)=NULL (expected africa.com)
psl_registrable_domain(amursk.ru)=NULL (expected amursk.ru)
psl_registrable_domain(appspot.com)=NULL (expected appspot.com)
psl_registrable_domain(ar.com)=NULL (expected ar.com)
psl_registrable_domain(eu.org)=NULL (expected eu.org)
psl_registrable_domain(nsk.ru)=NULL (expected nsk.ru)
```

([full test log](https://travis-ci.org/pshevtsov/publicsuffix-list/builds/98612042))

**Comment by sleevi** [comment]
That sounds like a bug with libpsl, not with the list; it's unclear what you see the issue as.

**Comment by pshevtsov** [comment]
I got the same results with [tldjs](https://www.npmjs.com/package/tldjs): https://jsfiddle.net/d0xe4ybk/1/ and also with [x/net/publicsuffix](https://godoc.org/golang.org/x/net/publicsuffix) Golang package.

**Comment by sleevi** [comment]
That doesn't really address my point; what you just said sounds like bugs in their implementation.

The test cases provided are consistent with the algorithm definition; if you're getting bad results, it's worth diving into the implementations and finding out why. For example, has a change in the format of the list produced invalid results?

Note that the test is *not* meant to be equivalent of `psl_registerable_domain`; that is, the function `checkPublicSuffix` is not equivalent to returning the registerable portion of the domain, but the public suffix.

The distinction is perhaps more obvious when you consider `foo.amber.museum`; the registerable portion of that domain is `foo.amber.museum`, the public suffix is `amber.museum`. This is similar to how `.com` is handled - `example.com` is the registerable domain, while `.com` is the public suffix. The function invoked by the tests is akin to `checkPublicSuffix('com', 'com')`

**Comment by sleevi** [comment]
er, sorry on the remark on `checkPublicSuffix('com', 'com')` - we actually have a test case for that in https://raw.githubusercontent.com/publicsuffix/list/master/tests/test_psl.txt

Since `appspot.com` (and all the other domains) are on the list, the results would be the same as `checkPublicSuffix('com'` - which is to say, all should return null.

The broader question/issue seems to be whether/how gaps are handled; that's primarily a question of spec and implementation ambiguity for which @gerv @weppos and others have been unable to find a clear and complete solution. I would point you to the older Bugzilla bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1139842 - which tracked a lot of this discussion about how gaps are handled and what the expected results are.

**Comment by rockdaboot** [comment]
As @sleevi says, the test cases should be like

checkPublicSuffix('amber.museum', NULL);
...

since 'amber.museum' and your other examples are public suffices.

**Comment by pshevtsov** [comment]
Thanks, got it!
