### ISSUE TITLE
TLD xn--qxa6a (ευ, greek "eu") is missing in PSL

### ISSUE THREAD

**Issue by jbg** [publicsuffix/list#936]
It's delegated from the root and recognised by IANA.

**Comment by dnsguru** [comment]
Wrote to government contact in ministry to find out their direction on next steps

**Comment by sleevi** [comment]
Thanks!

The current approach has the benefit of both failing closed and accurately
reflecting the current stated policy as efficiently as possible, which is
certainly good for embedders of the PSL.

Broadly speaking, I don’t think we want to replace wildcards with more
specific entries willy-nilly. If there are limited exceptions, we’d likely
want to use the exception syntax. If the 2LDs are the exception, rather
than the rule, then your PR is definitely how we’d handle it.

However, if the issue is just a matter of obtaining certs, it’s potentially
something specific to a CA. Normally, a CA can issue such certificates
fine, if they do additional due diligence validating the requestor controls
the namespace (e.g. that the request is from the duly authorized registry).
That only works if the CA is willing to do that validation - e.g. by
hand/manually, which not all CAs are willing to do. Understanding more of
the context is useful to trying to understand the problem here.

If, for example, they were trying to get a cert for domains.fj, it might
make perfect sense to list, as exception rules, !domains.fj and any other
directly-registry-operated domains.

Overall, I really appreciate you reaching out to them. Certainly, I don’t
see any problems with the parent record validating any child records; after
all, that’s how DNS works. But I do want to make sure we solve the right
problem as efficiently as possible 😊

**Comment by jbg** [comment]
Is there some context missing above? BTW, .ευ is a TLD, not a 2LD.

**Comment by sleevi** [comment]
Sorry, that reply (now deleted) was for a different issue.

**Comment by dnsguru** [comment]
I just submitted PR #966  for this

**Comment by weppos** [comment]
@dnsguru I approved the PR. Feel free to squash merge. Do you happen to know if there's any source where we can pull these TLDs?

**Comment by sleevi** [comment]
They are delegated in the Root Zone Database, which we intentionally don’t
pull from automatically (see the PR where we added the automatic
integration)
