### ISSUE TITLE
google.com missing in list?

### ISSUE THREAD

**Issue by wederer** [publicsuffix/list#985]
This might be a dumb question, but how come "google.com" is not in the public suffix list?
Is "google.com" hardcoded as a suffix in the browsers?

e.g. 
drive.google.com
mail.google.com
...

**Comment by sleevi** [comment]
Because Google has not requested it.

The existence of subdomains doesn’t make a public suffix. In Google’s example, it controls each of those subdomains and the content on them. Further, it shares cookies among those domains.

The existence of `drive.google.com` is no different than the existence of `www.google.com` - it’s just a subdomain.
